### ISSUE TITLE
Moons sometimes not showing and speed lines

### ISSUE THREAD

**Issue by Zekrodiak** [HolographicWings/LethalExpansion#1]
Sometimes moons don't appear. I had this issue after going to the company, also the speed lines that appear on the monitor when traveling to another moon shows up once then stops if you pick another location again before landing. 

sorry for edit I thought your mod was giving me fps issues but it was another one.

P.S I think it would be a cool idea if you make the monitor appear with color instead of keeping it green (if it's possible) so we can see the moons clearly.

**Comment by HolographicWings** [comment]
Hello, could you show me a video or screenshots of when the mood don't appear ?
And tell me if theres any error in the console or just send me the logs here after the issue happened
Really thanks

I plan to do things with the monitors in future, i edited the 8 screens monitor to make each screen use an independant material, so i keep your suggestion somewhere ^^

**Comment by HolographicWings** [comment]
> Sometimes moons don't appear. I had this issue after going to the company, also the speed lines that appear on the monitor when traveling to another moon shows up once then stops if you pick another location again before landing.
> 
> sorry for edit I thought your mod was giving me fps issues but it was another one.
> 
> P.S I think it would be a cool idea if you make the monitor appear with color instead of keeping it green (if it's possible) so we can see the moons clearly.

Hello, could you show me a video or screenshots of when the mood don't appear ?
And tell me if theres any error in the console or just send me the logs here after the issue happened
Really thanks

I plan to do things with the monitors in future, i edited the 8 screens monitor to make each screen use an independant material, so i keep your suggestion somewhere ^^

**Comment by Zekrodiak** [comment]
the limit here is 10mb for a file so ima share it trough google drive. I made 2 videos.

https://drive.google.com/file/d/1AuC28TwePhJAfs5odXSDIUWPXgc_j_lt/view?usp=sharing, https://drive.google.com/file/d/1DJMY1dXOuUfQ6eAQ-D9Z1NxqHtkN1KcR/view?usp=sharing

**Comment by HolographicWings** [comment]
> I made 2 videos. One shows when speed lines don't show anymore, and the other when planets stop appearing after exiting the company. Hope it helps. 👍
> 
> https://drive.google.com/file/d/1AuC28TwePhJAfs5odXSDIUWPXgc_j_lt/view?usp=sharing, https://drive.google.com/file/d/1DJMY1dXOuUfQ6eAQ-D9Z1NxqHtkN1KcR/view?usp=sharing

I fixed the moons stop appearing after leaving the Company Building
I'm investigating about the speedlines

**Comment by Zekrodiak** [comment]
It's fixed 🙌 
If you manage to fix the speed lines that would be awesome. makes it look more immersive.

Thanks for the quick update. your mod is amazing and I cant wait to see what else it would bring in the future cuz it has a lot of potential. 🔥

Keep up the good work! 💪

**Comment by HolographicWings** [comment]
Well, closing the issue then
