### ISSUE TITLE
Constant config syncing is creating lag spikes for non-host players

### ISSUE THREAD

**Issue by janlout** [HolographicWings/LethalExpansion#10]
Title pretty much says it all. The constant syncing of the config from host to players is creating lagspikes ofr the non-host players. A fix could possibly be to onlay syny the config when a new player joins and when the host updates the config.
Me and my friends tested this while being on the ship on  a fresh save. We confirmed it is your mod.

**Comment by HolographicWings** [comment]
> Title pretty much says it all. The constant syncing of the config from host to players is creating lagspikes ofr the non-host players. A fix could possibly be to onlay syny the config when a new player joins and when the host updates the config. Me and my friends tested this while being on the ship on a fresh save. We confirmed it is your mod.

It's already the case
Send me logs

The sync is supposed to happen each time a player is joining

**Comment by HolographicWings** [comment]
no answer, i close the issue.
