### ISSUE TITLE
need help with configs not working, worked before

### ISSUE THREAD

**Issue by kkbnnn** [HolographicWings/LethalExpansion#100]
this is on both the lastest version of the game and the latest version of the mod.
i've changed the configs for the starting quotas, starting credits, time speed before, they worked fine until one day they didn't.
the bepinex log that pops up on a modded game launch indicates that this mod is targeting a newer version of bepinex that isn't on thunderstore, 5.4.22.0, the one on that site or mod manager is 5.4.21.0. 

will me and everyone else using the configured mod need to install the newer version to allow my configs to work again? thank you for your help in advance!

**Comment by HolographicWings** [comment]
> this is on both the lastest version of the game and the latest version of the mod. i've changed the configs for the starting quotas, starting credits, time speed before, they worked fine until one day they didn't. the bepinex log that pops up on a modded game launch indicates that this mod is targeting a newer version of bepinex that isn't on thunderstore, 5.4.22.0, the one on that site or mod manager is 5.4.21.0.
> 
> will me and everyone else using the configured mod need to install the newer version to allow my configs to work again? thank you for your help in advance!

the version of bepinex will change nothing, did you changed the configuration with the settings menu ?

**Comment by kkbnnn** [comment]
thank you for your response! yes, i have changed and double checked everything in both the mod manager, in-game mod settings and even in the config file itself on my pc. it worked before but now it doesn't 
![config](https://github.com/HolographicWings/LethalExpansion/assets/157316002/41f0d709-2dfc-4629-b502-0fbf8631bce5)

**Comment by BuffMage** [comment]
Do you have LethalExpansionCore installed? It may be interfering with loading any of the settings here, since LEC overrides LE, you can disable this functionality in LEC's config in the setting `UseOriginalLethalExpansion` by setting it to `true`.

**Comment by kkbnnn** [comment]
thank you very much, that fixed it! i'm guessing one of us must have been messing around with a config and set it to the wrong one in confusion of what it actually did. cheers friends

**Comment by HolographicWings** [comment]
> thank you for your response! yes, i have changed and double checked everything in both the mod manager, in-game mod settings and even in the config file itself on my pc. it worked before but now it doesn't 
> ![config](https://github.com/HolographicWings/LethalExpansion/assets/157316002/41f0d709-2dfc-4629-b502-0fbf8631bce5)
> 

@kkbnnn 
Excuse me, what mod edits the monitors ? I'm curious about it
