### ISSUE TITLE
BiggerLobby Mod incompatible with LethalExpansion Mod

### ISSUE THREAD

**Issue by Lennozeros** [HolographicWings/LethalExpansion#103]
Yeah the title already says everything about it!

I mean its not a bug but its annoying because de-sync accure

**Comment by HolographicWings** [comment]
Yes we know, it's why there's a popup that tell you about incompatibility when you boot the game

**Comment by HolographicWings** [comment]
> [Lennozeros](/Lennozeros)

yes we know, both mods patch the chat in an incompatible way

**Comment by Lennozeros** [comment]
Aight, thank you!
