### ISSUE TITLE
Prevents me from playing the game

### ISSUE THREAD

**Issue by Lennozeros** [HolographicWings/LethalExpansion#104]
![20240126222547_1](https://github.com/HolographicWings/LethalExpansion/assets/105566375/551de9c8-569b-49c7-9a23-08c20d659644)

I hope the picture loads properly but thats basically it... its says the deadline is in 7 days and 3 hours and the quota is 509. When I try to start the ship nothing happens + it says if I really want to do it because I only have 0 days left.

I disabled and reanabled the mod and it came to the result, that the mod is doing so.

**Comment by HolographicWings** [comment]
> ![20240126222547_1](https://private-user-images.githubusercontent.com/105566375/300119104-551de9c8-569b-49c7-9a23-08c20d659644.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYzNjc5NTUsIm5iZiI6MTcwNjM2NzY1NSwicGF0aCI6Ii8xMDU1NjYzNzUvMzAwMTE5MTA0LTU1MWRlOWM4LTU2OWItNDljNy05YTIzLTA4YzIwZDY1OTY0NC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyN1QxNTAwNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02OWI4MGNhM2ZjYjBmYzE2OTk0ZDcyODc4ZDk1OTRmNGE4ZTFiMDliYzE4ZmRmOWNiYjdjZDg5ZTg2MjdlNDk4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4GMEB8dDT6DVM2bXft8JHRKNLWArYpl_hN71TxpRAjM)
> 
> I hope the picture loads properly but thats basically it... its says the deadline is in 7 days and 3 hours and the quota is 509. When I try to start the ship nothing happens + it says if I really want to do it because I only have 0 days left.
> 
> I disabled and reanabled the mod and it came to the result, that the mod is doing so.

without logs we can't do anything

**Comment by Lennozeros** [comment]
Hey,

It turned out to not be because of this mod. I just had bad luck with the timing but some kind of other mod is responsable for this bug. So no worries, everything seems to be fine! :D

**Comment by Lennozeros** [comment]
> > ![20240126222547_1](https://private-user-images.githubusercontent.com/105566375/300119104-551de9c8-569b-49c7-9a23-08c20d659644.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYzNjc5NTUsIm5iZiI6MTcwNjM2NzY1NSwicGF0aCI6Ii8xMDU1NjYzNzUvMzAwMTE5MTA0LTU1MWRlOWM4LTU2OWItNDljNy05YTIzLTA4YzIwZDY1OTY0NC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyN1QxNTAwNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02OWI4MGNhM2ZjYjBmYzE2OTk0ZDcyODc4ZDk1OTRmNGE4ZTFiMDliYzE4ZmRmOWNiYjdjZDg5ZTg2MjdlNDk4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4GMEB8dDT6DVM2bXft8JHRKNLWArYpl_hN71TxpRAjM)
> > I hope the picture loads properly but thats basically it... its says the deadline is in 7 days and 3 hours and the quota is 509. When I try to start the ship nothing happens + it says if I really want to do it because I only have 0 days left.
> > I disabled and reanabled the mod and it came to the result, that the mod is doing so.
> 
> without logs we can't do anything can you send the logs here please ?

Hey,

It turned out to not be because of this mod. I just had bad luck with the timing but some kind of other mod is responsable for this bug. So no worries, everything seems to be fine! :D

**Comment by Lennozeros** [comment]
> > ![20240126222547_1](https://private-user-images.githubusercontent.com/105566375/300119104-551de9c8-569b-49c7-9a23-08c20d659644.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYzNjc5NTUsIm5iZiI6MTcwNjM2NzY1NSwicGF0aCI6Ii8xMDU1NjYzNzUvMzAwMTE5MTA0LTU1MWRlOWM4LTU2OWItNDljNy05YTIzLTA4YzIwZDY1OTY0NC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyN1QxNTAwNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02OWI4MGNhM2ZjYjBmYzE2OTk0ZDcyODc4ZDk1OTRmNGE4ZTFiMDliYzE4ZmRmOWNiYjdjZDg5ZTg2MjdlNDk4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4GMEB8dDT6DVM2bXft8JHRKNLWArYpl_hN71TxpRAjM)
> > I hope the picture loads properly but thats basically it... its says the deadline is in 7 days and 3 hours and the quota is 509. When I try to start the ship nothing happens + it says if I really want to do it because I only have 0 days left.
> > I disabled and reanabled the mod and it came to the result, that the mod is doing so.
> 
> without logs we can't do anything can you send the logs here please ?

Hey,

It turned out to not be because of this mod. I just had bad luck with the timing but some kind of other mod is responsable for this bug. So no worries, everything seems to be fine! :D
