### ISSUE TITLE
[COMPATIBILITY] Removing Moons in other Mods

### ISSUE THREAD

**Issue by Mr-Twave** [HolographicWings/LethalExpansion#106]
In attempts to remove select moons from
{
https://thunderstore.io/c/lethal-company/p/Generic_GMD/Generic_Moons/
https://thunderstore.io/c/lethal-company/p/Dafini/Dafis_Mega_Moon_Pack_Emporium/
https://thunderstore.io/c/lethal-company/p/sfDesat/Orion/
}

Possibly interfering mods;
{
https://thunderstore.io/c/lethal-company/p/Magic_Wesley/Infernis/
https://thunderstore.io/c/lethal-company/p/KayNetsua/E_Gypt_Moon/
}

Log:
[LogOutput.log](https://github.com/HolographicWings/LethalExpansion/files/14077594/LogOutput.log)

I could not remove moons by using the comma separations. I tried with spaces and without spaces in the LethalConfig.

**Comment by HolographicWings** [comment]
> In attempts to remove select moons from https://thunderstore.io/c/lethal-company/p/Generic_GMD/Generic_Moons/ https://thunderstore.io/c/lethal-company/p/Dafini/Dafis_Mega_Moon_Pack_Emporium/ https://thunderstore.io/c/lethal-company/p/sfDesat/Orion/
> 
> Possibly interfering mods; https://thunderstore.io/c/lethal-company/p/Magic_Wesley/Infernis/ https://thunderstore.io/c/lethal-company/p/KayNetsua/E_Gypt_Moon/
> 
> Log: [LogOutput.log](https://github.com/HolographicWings/LethalExpansion/files/14077594/LogOutput.log)
> 
> I could not remove moons by using the comma separations. I tried with spaces and without spaces in the LethalConfig.

Unsure to understand, why do you want to remove theses moons instead of uninstalling them ?

**Comment by Mr-Twave** [comment]
Specifically, I tried removing the moons from dafis mega moon pack emporium when I had all of these mods installed. I cannot separate moons within this pack without affecting source directly.

**Comment by HolographicWings** [comment]
I don't understand what you are doing
What command to remove a moon ?

**Comment by HolographicWings** [comment]
I don't understand what you are doing
What command and why do you have theses moons installed twice ?

**Comment by Mr-Twave** [comment]
LethalExpansion(core) config;
ExcludedMoons - hidden,Wateridge,Windfallfall Island,The Moon,Chao Garden

The moons "windfallfall island", "the moon", and "chao garden" still show after excluding them.

... How do I have these moons installed twice? I have a bunch of moons installed.

**Comment by HolographicWings** [comment]
> LethalExpansion(core) config; ExcludedMoons - hidden,Wateridge,Windfallfall Island,The Moon,Chao Garden
> 
> The moons "windfallfall island", "the moon", and "chao garden" still show after excluding them.
> 
> ... How do I have these moons installed twice? I have a bunch of moons installed.

I haven't made LethalExpansion core, this is not my mod

**Comment by Mr-Twave** [comment]
Apologies. I'll transfer this to the correct git.

**Comment by HolographicWings** [comment]
No worries ^^"

**Comment by Mr-Twave** [comment]
![image](https://github.com/HolographicWings/LethalExpansion/assets/68743991/23480647-55cb-40da-bb8b-ea62c9c6dd21)

**Comment by HolographicWings** [comment]
LethalExpansion and LethalExpansion Core are two different mods
The setting is from LethalExpansion Core
