### ISSUE TITLE
Not an issue just a question.

### ISSUE THREAD

**Issue by lilswisher** [HolographicWings/LethalExpansion#107]
How can i get the skybox to update to a custom skybox? I've tried countless amounts of times to change it I just cant seem to get anything to work? Is it baked in? Like I changed the cubemap in the lighting tab while in unity however it still keeps displaying the default cloud skybox?

**Comment by HolographicWings** [comment]
> How can i get the skybox to update to a custom skybox? I've tried countless amounts of times to change it I just cant seem to get anything to work? Is it baked in? Like I changed the cubemap in the lighting tab while in unity however it still keeps displaying the default cloud skybox?

create a new volume profile
