### ISSUE TITLE
missing scrap options

### ISSUE THREAD

**Issue by ViViKoMods** [HolographicWings/LethalExpansion#11]
Would be great if you added some of the missing scrap options like twohanded & conductive etc

**Comment by HolographicWings** [comment]
> Would be great if you added some of the missing scrap options like twohanded & conductive etc

oh wait, i though about them and forgot them ! thanks you for reminding me it

**Comment by GoblinFiend** [comment]
^^^^^ I am really excited for this change :)

**Comment by subzerohurley** [comment]
Could we also get the option to play an audio file when the player interreacts with it while holding it? (Clicks while holding it)

**Comment by HolographicWings** [comment]
> Could we also get the option to play an audio file when the player interreacts with it while holding it? (Clicks while holding it)

planned in future, a lot to do for now, i can't prioritize this addition
