### ISSUE TITLE
Weird issue with Lethal expansion latest version.

### ISSUE THREAD

**Issue by Dragongas2003** [HolographicWings/LethalExpansion#12]
I've been using this mod in my modpack and when I updated the mod to its latest version it suddenly stopped working so I went back to the older version and it was working again. when looking into logs this seems to be the error that causes it not to load.

![Screenshot 2023-12-14 130056](https://github.com/HolographicWings/LethalExpansion/assets/153855526/cf5af610-818d-4121-b970-8fe8e8c9956d)

**Comment by Dragongas2003** [comment]
[LogOutput.log](https://github.com/HolographicWings/LethalExpansion/files/13677175/LogOutput.log)
in case u need it here is the full output log

**Comment by HolographicWings** [comment]
> [LogOutput.log](https://github.com/HolographicWings/LethalExpansion/files/13677175/LogOutput.log) in case u need it here is the full output log

You tried to load an outdated module, i did a fix about it, but ain't released it yet

**Comment by Dragongas2003** [comment]
ok thanks for the help

**Comment by LilMatsch** [comment]
> You tried to load an outdated module, i did a fix about it, but ain't released it yet
Do you already have a release date? Because I have the same problem and would love to play with this mod

**Comment by subzerohurley** [comment]
Even without the modules, it doesnt work it seems

**Comment by HolographicWings** [comment]
> Even without the modules, it doesnt work it seems

which module exactly ?

**Comment by subzerohurley** [comment]
Doesnt seem to matter, Can be one, can be all, Latest version isnt working. I removed template, port, left Expansion obviously

**Comment by subzerohurley** [comment]
Also would appreciate if this pop up didnt exist when going back down to a working version 😅
![image](https://github.com/HolographicWings/LethalExpansion/assets/18029175/39479eac-4a44-4dcc-a4ac-dd48ac8ac045)

**Comment by HolographicWings** [comment]
> Doesnt seem to matter, Can be one, can be all, Latest version isnt working. I removed template, port, left Expansion obviously 

If you have the GetVersion() issue it's an outdated module
I will add a retrocompatibility today but other devs must update their modules

**Comment by HolographicWings** [comment]
> Also would appreciate if this pop up didnt exist when going back down to a working version 😅
> ![image](https://github.com/HolographicWings/LethalExpansion/assets/18029175/39479eac-4a44-4dcc-a4ac-dd48ac8ac045)
> 

This is not supposed to happen Oo
This popup must show only in main menu
Send me logs after this happen

**Comment by HolographicWings** [comment]
The GetVersion() issue will be fixed this morning in 1.2.6
But again, the peoples who made the modules must keep them up to date
Retrocompatibility don't suit well with the network rework I done in 1.2.0

**Comment by HolographicWings** [comment]
Fixed, i close the issue
