### ISSUE TITLE
Moons fail to load if more than one LethalExpansion module is installed

### ISSUE THREAD

**Issue by andymwat** [HolographicWings/LethalExpansion#125]
When playing with friends using a set of mods that included two LethalExpansion modules ([UmaCompany](https://thunderstore.io/c/lethal-company/p/qwcan/UmaCompany/) and [FumoCompany](https://thunderstore.io/c/lethal-company/p/silhygames/FumoCompany/])), moons would fail to load, staying on the "Random Seed: XXXXXXX" screen forever, with everyone free to move around the ship (but everyone else saw the "Waiting for players..." screen). After some testing, we narrowed it down to only happening when both of the modules were installed. If only one was enabled, everything would work fine. Having both installed caused the problem, but only when there were multiple players on the server. When playing alone, the game worked as normal, even if both were installed. 

To reproduce:
- Install BepInEx, LethalExpansion, [UmaCompany](https://thunderstore.io/c/lethal-company/p/qwcan/UmaCompany/) and [FumoCompany](https://thunderstore.io/c/lethal-company/p/silhygames/FumoCompany/])
- Start a new game
- Have at least one person join the server
- Land, take off, then attempt to land again

**Comment by HolographicWings** [comment]
Hello, send me logs please

**Comment by andymwat** [comment]
[LogOutput.log](https://github.com/HolographicWings/LethalExpansion/files/14366333/LogOutput.log)

Short video of the issue:
https://github.com/HolographicWings/LethalExpansion/assets/42820057/703a76d7-9d5d-440d-972d-e78bb12f2dbd

**Comment by andymwat** [comment]
This may be related, I also noticed that when we first installed my mod (UmaCompany), some existing scrap from FumoCompany turned into scrap from UmaCompany.

**Comment by HolographicWings** [comment]
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
RoundManager.SyncScrapValuesClientRpc (Unity.Netcode.NetworkObjectReference[] spawnedScrap, System.Int32[] allScrapValue) 

I will try tomorrow if I find the time
Did you reported the issue to the modders of theses two modules too ?

**Comment by andymwat** [comment]
I reported it to the creator of the FumoCompany module. I am the creator of the UmaCompany module.

**Comment by HolographicWings** [comment]
the issue seems random, one of the scrams may be missconfigured
could you try with only Fumo then only Uma ? To know which of theses mods have the issue
On your side, check the network object script of all the scraps, one of them may have a different configuration than the others
Tells the Fumo's dev to do it too

**Comment by HolographicWings** [comment]
the issue seems random, one of the scraps may be missconfigured
i got it only with Uma
Check the network object script of all the scraps, one of them may have a different configuration than the others

**Comment by HolographicWings** [comment]
releasing an update that will skip the scraps with missing mesh filter
![image](https://github.com/HolographicWings/LethalExpansion/assets/19623115/affbee76-d8cc-403c-b3bf-2ef6742a89aa)

**Comment by andymwat** [comment]
> it seems some of your scraps don't have any meshfilters, at least the error tells it when deep debugging it vanilla code calls the meshfilter of scraps
> 
> ![image](https://private-user-images.githubusercontent.com/19623115/307522656-543ccfa7-fc3d-418a-a0cb-99fc0ecadf8f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg3OTA3MzYsIm5iZiI6MTcwODc5MDQzNiwicGF0aCI6Ii8xOTYyMzExNS8zMDc1MjI2NTYtNTQzY2NmYTctZmMzZC00MThhLWEwY2ItOTlmYzBlY2FkZjhmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI0VDE2MDAzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlNjAyZTVhMGRkMWY2NjJkNjlmM2FiMWIyNzRlY2M0NWI0Nzg3NTI5MjMyMzVjY2JmZThhMmQzNDY2MDQ2NjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bAIYYmtsyO5P4S1fI6tnRSvGY_FaQVq4FC4F98eavQM) ![image](https://private-user-images.githubusercontent.com/19623115/307522724-e760678f-3e85-403f-a942-4bf88f5835d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg3OTA3MzYsIm5iZiI6MTcwODc5MDQzNiwicGF0aCI6Ii8xOTYyMzExNS8zMDc1MjI3MjQtZTc2MDY3OGYtM2U4NS00MDNmLWE5NDItNGJmODhmNTgzNWQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI0VDE2MDAzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczN2FhYjAxYmEzMjU5Mjc0MjM1YjlmM2VmNThiM2ViNzhhZGU3NTI5NmRmZGMwMzFjYjIyZGQzMDQwYjYyOWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cFUKOvZdiexwWsJZS8fhz4PZbdN9EV4dKquKFGcnm5M)

All of my scrap items have a meshfilter, but they're in a child object of the main gameobject:
![image](https://github.com/HolographicWings/LethalExpansion/assets/42820057/4054c44d-4187-4fe8-a2f0-beeec78c74b1)
I did it this way to simplify getting the rotation right and work around an issue where the "Bake Axis Conversion" import setting on the model wasn't being respected when playing in multiplayer (the model would appear rotated 90 degrees into the ground). I figured that this was fine, as they appeared just fine in game.

**Comment by HolographicWings** [comment]
Unfortunately the vanilla code get the meshfilter of the parent object :/

**Comment by andymwat** [comment]
I just switched things around so that the meshes are on the parent objects, I'll let you know if that fixes the issue.

**Comment by andymwat** [comment]
That seems to have fixed it. I'll do a longer test tonight, and if that that works I'll close the issue.
