### ISSUE TITLE
Scrap with no Mesh Filter aren't getting registered

### ISSUE THREAD

**Issue by Just2407** [HolographicWings/LethalExpansion#131]
This itself is no problem, but it gets problematic, when you have scrap consisting of multiple parts.
Every part is a child object and has a mesh filter of its own but the parent doesn't have one and because of this the scrap gets skipped.

I could avoid this problem by simply adding a mesh filter with no mesh to the parent and now it gets registered, but maybe the checkup could also check for any children with mesh filters.

**Comment by HolographicWings** [comment]
> This itself is no problem, but it gets problematic, when you have scrap consisting of multiple parts. Every part is a child object and has a mesh filter of its own but the parent doesn't have one and because of this the scrap gets skipped.
> 
> I could avoid this problem by simply adding a mesh filter with no mesh to the parent and now it gets registered, but maybe the checkup could also check for any children with mesh filters.

unfortunately the vanilla code calls for a mesh filter in the parent object of a scrap, without, it will make an issue when syncing the scraps between all the players and avoid loading
https://github.com/HolographicWings/LethalExpansion/issues/125

**Comment by Just2407** [comment]
Okay interesting. Thanks for the answer.
