### ISSUE TITLE
Please fix the new update fast 1.2.5 - Incompatible and Issue banner on every old versions

### ISSUE THREAD

**Issue by Snaetsh** [HolographicWings/LethalExpansion#14]
Written with translator:

The new update means that new moons that previously existed will no longer be recognized. In addition, in all old versions that still work, a "thick" banner is always displayed and you should please update, but you can't even click away from this banner in the game. Please please, as long as the new update is not compatible, remove these really annoying banners from old versions that make it impossible to play and prevent you from currently being able to leave any of your mods in the list. Please help quickly. I love your Lethal Company mod, but then it probably has to go.

For this post I must had to create an github account - please help

**Comment by Snaetsh** [comment]
Same Issue here :

https://github.com/HolographicWings/LethalSDK-Unity-Project/issues/16
https://github.com/HolographicWings/LethalExpansion/issues/12

**Comment by Snaetsh** [comment]
Same Issue here :

https://github.com/HolographicWings/LethalSDK-Unity-Project/issues/16

**Comment by Snaetsh** [comment]
Same Issue here :

https://github.com/HolographicWings/LethalSDK-Unity-Project/issues/16
https://github.com/HolographicWings/LethalExpansion/issues/12

**Comment by Snaetsh** [comment]
Same Issue here :

https://github.com/HolographicWings/LethalSDK-Unity-Project/issues/16

https://github.com/HolographicWings/LethalExpansion/issues/12

**Comment by Snaetsh** [comment]
Please remove the banner that we should upate when the game (party) has already started. We can accept that.

**Comment by HolographicWings** [comment]
> hat.

Send me logs after the popup showing, it's supposed to show only in main menu

**Comment by GoblinFiend** [comment]
Hello, I see that you have updated the mod to 1.2.6 and It has seemed to fix something- but the custom moons and custom scraps still do not seem to load into the game. In the log, it states that the new assets are loaded but in game it does not work and the moons menu is default. Trying to get some custom assets to work but can't test them in game without the mod functioning fully. Sorry for telling you about this again but I just wanted to let you know that the issue still persists. Hope it gets resolved soon and ends up being easy for you :). I'll include my Log, but this is just the mod installed as is with no extra personal assets upon loading into the ship. Thanks for all your hard work!

[LogOutput.log](https://github.com/HolographicWings/LethalExpansion/files/13683673/LogOutput.log)

**Comment by Snaetsh** [comment]
In main menu : ![image](https://github.com/HolographicWings/LethalExpansion/assets/153874558/646f750a-9be5-43be-bb3a-b51a0e442093)f) 

In game popup : ![image](https://github.com/HolographicWings/LethalExpansion/assets/153874558/d95da1a3-a5d9-4d93-8465-89a079e3b12b)

In game popup : 
![image](https://github.com/HolographicWings/LethalExpansion/assets/153874558/c2bb9522-8351-497c-be68-a29357787109)

**Comment by HolographicWings** [comment]
> Hello, I see that you have updated the mod to 1.2.6 and It has seemed to fix something- but the custom moons and custom scraps still do not seem to load into the game. In the log, it states that the new assets are loaded but in game it does not work and the moons menu is default. Trying to get some custom assets to work but can't test them in game without the mod functioning fully. Sorry for telling you about this again but I just wanted to let you know that the issue still persists. Hope it gets resolved soon and ends up being easy for you :). I'll include my Log, but this is just the mod installed as is with no extra personal assets upon loading into the ship. Thanks for all your hard work!
> 
> [LogOutput.log](https://github.com/HolographicWings/LethalExpansion/files/13683673/LogOutput.log)

everything seems to be normal in your log
can you send me some screenshots or video of your issue ?

**Comment by HolographicWings** [comment]
> In main menu : ![image](https://private-user-images.githubusercontent.com/153874558/290795494-646f750a-9be5-43be-bb3a-b51a0e442093.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2MzYxODMsIm5iZiI6MTcwMjYzNTg4MywicGF0aCI6Ii8xNTM4NzQ1NTgvMjkwNzk1NDk0LTY0NmY3NTBhLTliZTUtNDNiZS1iYjNhLWI1MWEwZTQ0MjA5My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxNVQxMDI0NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YWNiMzQ5ZjM0NzJjNDk4ZTE3YzIxNTMxODg4YzFiMmIyODA2MGQ2N2I5ZjYwOTVmYzI1ZDk2MmJjMDJkYmMyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZqsgBTxRGSRhuAAER0JYlxPNh30teH0koa8jK6aVwjY)f)
> 
> In game popup : ![image](https://private-user-images.githubusercontent.com/153874558/290795881-d95da1a3-a5d9-4d93-8465-89a079e3b12b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2MzYxODMsIm5iZiI6MTcwMjYzNTg4MywicGF0aCI6Ii8xNTM4NzQ1NTgvMjkwNzk1ODgxLWQ5NWRhMWEzLWE1ZDktNGQ5My04NDY1LTg5YTA3OWUzYjEyYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxNVQxMDI0NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZmU2MDkxZjU2ZmEzMWRmMGZkOTkwYjI3NGViZDYyYWQxODUxZGZiMDgzMjQ4ODdmOTU0NTk3OWU0MzdmYjY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.clZq2Ff4U3ypEusgMxjTardwyVTaVhi9NCKiw8a2hLY)
> 
> In game popup : ![image](https://private-user-images.githubusercontent.com/153874558/290796172-c2bb9522-8351-497c-be68-a29357787109.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2MzYxODMsIm5iZiI6MTcwMjYzNTg4MywicGF0aCI6Ii8xNTM4NzQ1NTgvMjkwNzk2MTcyLWMyYmI5NTIyLTgzNTEtNDk3Yy1iZTY4LWEyOTM1Nzc4NzEwOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxNVQxMDI0NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MDY2ZGY1OTliNGQ3Y2E5YTQ4NjBhYTQyNGZjYjZlZjVkNWY2OTM5Mzk0NTBmYTVlYjZlMWQxMjFjYzBkNGJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.29-qegx3drrTcjWoWh7EvogUSHFXsKyLklOLzdwWH-I)

i need a full log output

**Comment by Snaetsh** [comment]
![image](https://github.com/HolographicWings/LethalExpansion/assets/153874558/b3d15937-6d9a-4ae1-92f4-38f3ec9fcc5a)

![image](https://github.com/HolographicWings/LethalExpansion/assets/153874558/d5702e5a-c4aa-42cc-98f1-36f950154a4d)

**Comment by Snaetsh** [comment]
I don't know exactly in which line the popup should be created.

**Comment by HolographicWings** [comment]
> ![image](https://private-user-images.githubusercontent.com/153874558/290797018-b3d15937-6d9a-4ae1-92f4-38f3ec9fcc5a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2MzY0MDQsIm5iZiI6MTcwMjYzNjEwNCwicGF0aCI6Ii8xNTM4NzQ1NTgvMjkwNzk3MDE4LWIzZDE1OTM3LTZkOWEtNGFlMS05MmY0LTM4ZjNlYzlmY2M1YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxNVQxMDI4MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NGIzNjFiZjU4ZDFjZTJiNWMzYWU3OGZjYjg1ZmRiZGMzYzRjN2QzYmYyZmI4MDI4MDQwYjI3ZjZkYzliZWU0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._6aPOyC7LIbRZN9o8oV638_Q4SK00_f4N8OXp8ChykU)
> 
> ![image](https://private-user-images.githubusercontent.com/153874558/290797061-d5702e5a-c4aa-42cc-98f1-36f950154a4d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2MzY0MDQsIm5iZiI6MTcwMjYzNjEwNCwicGF0aCI6Ii8xNTM4NzQ1NTgvMjkwNzk3MDYxLWQ1NzAyZTVhLWM0YWEtNDJjYy05OGYxLTM2Zjk1MDE1NGE0ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxNVQxMDI4MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00OWJlOGFmODlmZDkwYjY2NzRhMGM3NWQwNzZhMjQ5NGViZjE3OWY4ZTk2ZDQ3MDA5NmM4ZTAxOTdlOTgzZThiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LrUSPzH8XQhn0zfLLuICXriMA7b0CBMtNn59cOb_M0g)

but did you updated the mod ???? i read 1.2.3

**Comment by HolographicWings** [comment]
> I don't know exactly in which line the popup should be created.

it's why you should send me a full log output

**Comment by Snaetsh** [comment]
Not yet. I'm now trying the new version :) Thank you very much for your efforts

**Comment by HolographicWings** [comment]
> Not yet. I'm now trying the new version :) Thank you very much for your efforts

but you are telling me your issue is the outdated message and you ain't updated your game ?...

**Comment by Snaetsh** [comment]
Exactly. I haven't updated it yet. Please wait, I'll remove all mods except yours and send you a complete log with the old version

**Comment by Snaetsh** [comment]
[Message:   BepInEx] BepInEx 5.4.21.0 - Lethal Company (09.12.2023 17:01:14)
[Info   :   BepInEx] Running under Unity v2022.3.9.15351836
[Info   :   BepInEx] CLR runtime version: 4.0.30319.42000
[Info   :   BepInEx] Supports SRE: True
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.Preloader 5.4.21.0]
[Info   :   BepInEx] 1 patcher plugin loaded
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Message:   BepInEx] Preloader finished
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 2 plugins to load
[Info   :   BepInEx] Loading [LC_API 2.1.4]
[Warning:    LC_API]
.____    _________           _____  __________ .___
|    |   \_   ___ \         /  _  \ \______   \|   |
|    |   /    \  \/        /  /_\  \ |     ___/|   |
|    |___\     \____      /    |    \|    |    |   |
|_______ \\______  /______\____|__  /|____|    |___|
        \/       \//_____/        \/

[Info   :    LC_API] LC_API Starting up..
[Info   :   BepInEx] Loading [LethalExpansion 1.2.3]
[Info   :LethalExpansion] PluginName: LethalExpansion, VersionString: 1.2.3 is loading...
[Info   :LethalExpansion] Getting other plugins list
[Info   :LethalExpansion] Plugin: LC_API - Version: 2.1.4 - Compatibility: good
[Info   :LethalExpansion] Module found: OldSeaPort
[Info   :LethalExpansion] Module found: TemplateMod
[Info   :LethalExpansion] Water support applied to the HDRenderPipelineAsset.
[Info   :LethalExpansion] PluginName: LethalExpansion, VersionString: 1.2.3 is loaded.
[Message:   BepInEx] Chainloader startup complete
[Info   : Unity Log] Changing gamma
[Info   : Unity Log] override float value: -0,05
[Info   : Unity Log] Overriding float
[Info   : Unity Log] Gamma changed
[Info   : Unity Log] Set gamma to new value: -0,05; (0.00, 0.00, 0.00, -0.05) (True)
[Info   :LethalExpansion] Loading scene: InitSceneLaunchOptions
[Message:    LC_API] BundleAPI will now load all asset bundles...
[Message:    LC_API] BundleAPI got no assets to load from legacy directory
[Message:    LC_API] BundleAPI got no assets to load from plugins folder
[Message:    LC_API] BundleAPI finished loading all assets.
[Message:    LC_API] BundleAPI finished loading all assets.
[Info   :    LC_API] LC_API Started!
[Warning: Unity Log] MaximizedWindow is not currently supported on Windows, setting to FullsceenWindow instead
[Info   : Unity Log] Saving changed settings
[Info   : Unity Log] Changing gamma
[Info   : Unity Log] override float value: -0,05
[Info   : Unity Log] Overriding float
[Info   : Unity Log] Gamma changed
[Info   : Unity Log] Set gamma to new value: -0,05; (0.00, 0.00, 0.00, -0.05) (True)
[Warning: Unity Log] MaximizedWindow is not currently supported on Windows, setting to FullsceenWindow instead
[Info   :LethalExpansion] Unloading scene: InitSceneLaunchOptions
[Info   : Unity Log] subcribing to steam callbacks
Setting breakpad minidump AppID = 1966720
SteamInternal_SetMinidumpSteamID:  Caching Steam ID:  76561199524253291 [API loaded no]
[Info   :LethalExpansion] Loading scene: InitScene
[Info   : Unity Log] Changing gamma
[Info   : Unity Log] override float value: -0,05
[Info   : Unity Log] Overriding float
[Info   : Unity Log] Gamma changed
[Info   : Unity Log] Set gamma to new value: -0,05; (0.00, 0.00, 0.00, -0.05) (True)
[Info   :LethalExpansion] Battery Scrap registered.
[Info   :LethalExpansion] Canned Food Scrap registered.
[Info   :LethalExpansion] Matchbox Scrap registered.
[Info   :LethalExpansion] Pills Scrap registered.
[Info   :LethalExpansion] Tape Scrap registered.
[Warning: Unity Log] MaximizedWindow is not currently supported on Windows, setting to FullsceenWindow instead
[Info   : Unity Log] [FacepunchTransport] - Initialized access to Steam Relay Network.
[Info   : Unity Log] [FacepunchTransport] - Fetched user Steam ID.
[Info   : Unity Log] SKIPPING aaaa
[Info   : Unity Log] SKIPPING
[Info   :LethalExpansion] Unloading scene: InitScene
[Info   : Unity Log] Set version num
[Info   :LethalExpansion] Loading scene: MainMenu
[Info   : Unity Log] Changing gamma
[Info   : Unity Log] override float value: -0,05
[Info   : Unity Log] Overriding float
[Info   : Unity Log] Gamma changed
[Info   : Unity Log] Set gamma to new value: -0,05; (0.00, 0.00, 0.00, -0.05) (True)
[Warning: Unity Log] MaximizedWindow is not currently supported on Windows, setting to FullsceenWindow instead

**Comment by HolographicWings** [comment]
do you even understand what the popup is telling ?

**Comment by Snaetsh** [comment]
yeah i should update the mod, but when only the old version is combatible - im forced to update, because i cant accept or refuse
the popup. Now i try the new update

**Comment by HolographicWings** [comment]
> yeah i should update the mod, but when only the old version is combatible - im forced to update, because i cant accept or refuse the popup. Now i try the new update

if theres another error with last version send it

**Comment by Snaetsh** [comment]
All right, I will, i try now

**Comment by Snaetsh** [comment]
thanks a lot. with the new version we have all new moons. thank u a lot

**Comment by HolographicWings** [comment]
okay, i close this issue, reopen it if theres any other problem

**Comment by GoblinFiend** [comment]
> > Hello, I see that you have updated the mod to 1.2.6 and It has seemed to fix something- but the custom moons and custom scraps still do not seem to load into the game. In the log, it states that the new assets are loaded but in game it does not work and the moons menu is default. Trying to get some custom assets to work but can't test them in game without the mod functioning fully. Sorry for telling you about this again but I just wanted to let you know that the issue still persists. Hope it gets resolved soon and ends up being easy for you :). I'll include my Log, but this is just the mod installed as is with no extra personal assets upon loading into the ship. Thanks for all your hard work!
> > [LogOutput.log](https://github.com/HolographicWings/LethalExpansion/files/13683673/LogOutput.log)
> 
> everything seems to be normal in your log can you send me some screenshots or video of your issue ? are you trying to add your own modules ?

Yeah everything is normal in the logs I noticed as well. I would like to add my own modules but no, they are not even added in. The mod works in version 1.2.6 (as I can change all mod settings in config or the main menu and it works) but once I load into the game I can tell that the moon and scrap modules didn't properly load in. (Such as battery, tape, canned food and the map wateridge). When I type "moons" into the terminal the modded moon menu doesn't show up and I can't route to wateridge. Upon loading into a map with scrap generation set 10x. I find no custom scrap items like the canned food or tape that are by default in LethalExpansion. Because of this I am unable to test my custom modules because the base ones don't work since v1.2.5 was released.  Going back to version 1.2.4 or earlier makes them load in properly again. Hope this helps give you some context. I believe it is an issue with version 1.2.5 that persists into 1.2.6.

**Comment by HolographicWings** [comment]
> > > Hello, I see that you have updated the mod to 1.2.6 and It has seemed to fix something- but the custom moons and custom scraps still do not seem to load into the game. In the log, it states that the new assets are loaded but in game it does not work and the moons menu is default. Trying to get some custom assets to work but can't test them in game without the mod functioning fully. Sorry for telling you about this again but I just wanted to let you know that the issue still persists. Hope it gets resolved soon and ends up being easy for you :). I'll include my Log, but this is just the mod installed as is with no extra personal assets upon loading into the ship. Thanks for all your hard work!
> > > [LogOutput.log](https://github.com/HolographicWings/LethalExpansion/files/13683673/LogOutput.log)
> > 
> > 
> > everything seems to be normal in your log can you send me some screenshots or video of your issue ? are you trying to add your own modules ?
> 
> Yeah everything is normal in the logs I noticed as well. I would like to add my own modules but no, they are not even added in. The mod works in version 1.2.6 (as I can change all mod settings in config or the main menu and it works) but once I load into the game I can tell that the moon and scrap modules didn't properly load in. (Such as battery, tape, canned food and the map wateridge). When I type "moons" into the terminal the modded moon menu doesn't show up and I can't route to wateridge. Upon loading into a map with scrap generation set 10x. I find no custom scrap items like the canned food or tape that are by default in LethalExpansion. Because of this I am unable to test my custom modules because the base ones don't work since v1.2.5 was released. Going back to version 1.2.4 or earlier makes them load in properly again. Hope this helps give you some context. I believe it is an issue with version 1.2.5 that persists into 1.2.6.

send me the zip containing the folder of your mod
and tell me if the mod work normally when you remove every external .lem module than the LethalExpansions one
if you want to talk quicker invite me on discord, it's same username
