### ISSUE TITLE
Custom Scrap isnt spawning

### ISSUE THREAD

**Issue by subzerohurley** [HolographicWings/LethalExpansion#16]
Even when everything is updated, the Module's were made using 1.2.0 SDK, nothing loads in. 
Not even the preset template. This was an issue introduced back in 1.2.5 of Expansion and was labeled "Fixed" under the assumption it was retrocompatibility. But even the built in stuff like the beans, tape, etc doesnt spawn.

**Comment by HolographicWings** [comment]
> Even when everything is updated, the Module's were made using 1.2.0 SDK, nothing loads in. Not even the preset template. This was an issue introduced back in 1.2.5 of Expansion and was labeled "Fixed" under the assumption it was retrocompatibility. But even the built in stuff like the beans, tape, etc doesnt spawn.

I need logs, i can't help you otherwise

**Comment by subzerohurley** [comment]
The last update actually seemed to have fixed it! thank you so much! 
Tho I do wanna ask, What's this setting for? 
![image](https://github.com/HolographicWings/LethalExpansion/assets/18029175/35df283e-b2c2-4961-95f8-ea05601abb5f)

**Comment by HolographicWings** [comment]
> The last update actually seemed to have fixed it! thank you so much! 
> Tho I do wanna ask, What's this setting for? 
> ![image](https://github.com/HolographicWings/LethalExpansion/assets/18029175/35df283e-b2c2-4961-95f8-ea05601abb5f)
> 

It's to set what other modules are required for your to work 
If the required are not loaded, your module will be skipped to avoid crashes

**Comment by subzerohurley** [comment]
Ah I see! Thank you for explaining it!
