### ISSUE TITLE
An Unsovled Problem

### ISSUE THREAD

**Issue by Minstrel2000** [HolographicWings/LethalExpansion#17]
I have the same bug mentioned in #12 ,which was said caused by outdated module.
However,when I remove all my module to test the Lethal expansion mod only,it still cant work.
Maybe I didnt get grasp of the solution,but here is the logoutput.
[LogOutput.log](https://github.com/HolographicWings/LethalExpansion/files/13690900/LogOutput.log)

**Comment by HolographicWings** [comment]
> I have the same bug mentioned in #12 ,which was said caused by outdated module. However,when I remove all my module to test the Lethal expansion mod only,it still cant work. Maybe I didnt get grasp of the solution,but here is the logoutput. [LogOutput.log](https://github.com/HolographicWings/LethalExpansion/files/13690900/LogOutput.log)

The error in the logs you sent tells about System.IO which is to read files on your disk
Check if have the proper permissions to access to the folder where the mod is installed
I invite you to test with the 1.2.7 i'm about to release and send me another log of the mod alone and with the other modules.

**Comment by Minstrel2000** [comment]
> > I have the same bug mentioned in #12 ,which was said caused by outdated module. However,when I remove all my module to test the Lethal expansion mod only,it still cant work. Maybe I didnt get grasp of the solution,but here is the logoutput. [LogOutput.log](https://github.com/HolographicWings/LethalExpansion/files/13690900/LogOutput.log)
> 
> The error in the logs you sent tells about System.IO which is to read files on your disk Check if have the proper permissions to access to the folder where the mod is installed I invite you to test with the 1.2.7 i'm about to release and send me another log of the mod alone and with the other modules.

Lethal expansion was installed in the same folder with any other mods existed before,so it may have little relation with the permissions,unless there is something special in this mod.And okay,I'll wait for the new version hoping it will fix the problem.

**Comment by Minstrel2000** [comment]
Still malfunction.
[LogOutput(alone).log](https://github.com/HolographicWings/LethalExpansion/files/13690983/LogOutput.alone.log)
[LogOutput(with mods).log](https://github.com/HolographicWings/LethalExpansion/files/13690984/LogOutput.with.mods.log)

**Comment by HolographicWings** [comment]
[Error  : Unity Log] IOException: 参数错误。 : 'D:\Application\Steam\steamapps\common\Lethal Company\BepInEx\plugins\HolographicWings-LethalExpansion-1.2.7\LethalExpansion.dll'
Stack trace:

the issue is about the file explorer
are you on windows 7 ?

**Comment by Minstrel2000** [comment]
> [Error : Unity Log] IOException: 参数错误。 : 'D:\Application\Steam\steamapps\common\Lethal Company\BepInEx\plugins\HolographicWings-LethalExpansion-1.2.7\LethalExpansion.dll' Stack trace:
> 
> the issue is about the C# file explorer are you on windows 7 ?

1.win11 exactly.
2.I just have a try,but it seems not the solution.

**Comment by HolographicWings** [comment]
> > [Error : Unity Log] IOException: 参数错误。 : 'D:\Application\Steam\steamapps\common\Lethal Company\BepInEx\plugins\HolographicWings-LethalExpansion-1.2.7\LethalExpansion.dll' Stack trace:
> > the issue is about the C# file explorer are you on windows 7 ?
> 
> 1.win11 exactly. 2.I just have a try,but it seems not the solution.

i don't understand, the issue could be from everywhere

**Comment by Minstrel2000** [comment]
So I just have another 2 tests.
1)Uninstall the game and remove all the files in Lethal Company to avoid anything that may affect the course,then install the game and the BepInEx,finally this mod.
2)Ask my friend to install this mod on his computer.
None of them works.The same problem show up.
So it seems not the problem caused by other mods or running circumstance.
If there are any other advices,please tell me,thanks.

**Comment by Minstrel2000** [comment]
Hey there's something new.
I tried every version you released before to find that the latest compatiable version is 1.1.6.So the problem is definitely have to do with the 1.1.7 updates,hope this may help you figure out the problem.

**Comment by HolographicWings** [comment]
> Hey there's something new.
> I tried every version you released before to find that the latest compatiable version is 1.1.6.So the problem is definitely have to do with the 1.1.7 updates,hope this may help you figure out the problem.

That may help a lot, I will check what changes could do that
Are you sure you mean 1.1.7 and not 1.2.7 ?

**Comment by Minstrel2000** [comment]
> > Hey there's something new.
> > I tried every version you released before to find that the latest compatiable version is 1.1.6.So the problem is definitely have to do with the 1.1.7 updates,hope this may help you figure out the problem.
> 
> That may help a lot, I will check what changes could do that Are you sure you mean 1.1.7 and not 1.2.7 ?

yeah it's 1.1.7

**Comment by HolographicWings** [comment]
> > > Hey there's something new.
> > > I tried every version you released before to find that the latest compatiable version is 1.1.6.So the problem is definitely have to do with the 1.1.7 updates,hope this may help you figure out the problem.
> > 
> > That may help a lot, I will check what changes could do that Are you sure you mean 1.1.7 and not 1.2.7 ?
> 
> yeah it's 1.1.7

I will check when I'll be up

**Comment by HolographicWings** [comment]
> > > > Hey there's something new.
> > > > I tried every version you released before to find that the latest compatiable version is 1.1.6.So the problem is definitely have to do with the 1.1.7 updates,hope this may help you figure out the problem.
> > > 
> > > That may help a lot, I will check what changes could do that Are you sure you mean 1.1.7 and not 1.2.7 ?
> > 
> > yeah it's 1.1.7
> 
> I will check when I'll be up

The rename the mod folder from HolographicWings-LethalExpansion-1.2.7
To HolographicWings-LethalExpansion

**Comment by Minstrel2000** [comment]
> > > > > Hey there's something new.
> > > > > I tried every version you released before to find that the latest compatiable version is 1.1.6.So the problem is definitely have to do with the 1.1.7 updates,hope this may help you figure out the problem.
> > > > 
> > > > 
> > > > That may help a lot, I will check what changes could do that Are you sure you mean 1.1.7 and not 1.2.7 ?
> > > 
> > > 
> > > yeah it's 1.1.7
> > 
> > 
> > I will check when I'll be up
> 
> Try to rename the mod folder from HolographicWings-LethalExpansion-1.2.7 To HolographicWings-LethalExpansion The version number is not supposed to show, why did it show like that ? It's a R2Modman setting ?

I install the mod by copying the file to the plugins folder without any other software(such as R2Modman).

**Comment by Minstrel2000** [comment]
It works.So that's the question.

**Comment by HolographicWings** [comment]
> It works.So that's the question.

I will adapt the modules loader for manual installs
Thanks you

**Comment by HolographicWings** [comment]
let me know if fixed @Minstrel2000

**Comment by Minstrel2000** [comment]
> let me know if fixed @Minstrel2000

the version 1.2.11 is proved to be compatiable,so I think this bug about manual installs is fixed.thanks :)
