### ISSUE TITLE
Modded moons not appearing

### ISSUE THREAD

**Issue by Dantoresco** [HolographicWings/LethalExpansion#18]
Modded moons were loading fine at the terminal in 1.2.6 but since the 1.2.7 and now the 1.2.8 neither Wateridge or Orion are appearing. The "Load SDK Module" option is turned on.

**Comment by HolographicWings** [comment]
> Modded moons were loading fine at the terminal in 1.2.6 but since the 1.2.7 and now the 1.2.8 neither Wateridge or Orion are appearing. The "Load SDK Module" option is turned on.

Logs please

**Comment by KickerMix** [comment]
Same here, can't get it to work with latest version of LE. Wateridge not appering in terminal since 1.2.7 update
[LogOutput.log](https://github.com/HolographicWings/LethalExpansion/files/13692216/LogOutput.log)

**Comment by HolographicWings** [comment]
> Same here, can't get it to work with latest version of LE. Wateridge not appering in terminal since 1.2.7 update
> [LogOutput.log](https://github.com/HolographicWings/LethalExpansion/files/13692243/LogOutput.log)
> 
> 

Ah yes
I forgot something I will add soon
Thanks you
Install the mod with R2Modman meanwhile

**Comment by HolographicWings** [comment]
Should be fixed, i let you try @KickerMix and @Dantoresco

**Comment by KickerMix** [comment]
> Should be fixed, i let you try @KickerMix and @Dantoresco

Works fine! Thanks, looking forward for further updates!

**Comment by HolographicWings** [comment]
okay i'm closing this issue then, thanks for reporting
