### ISSUE TITLE
The last update broke the StartingCredits, StartingQuota options

### ISSUE THREAD

**Issue by SrMoroxide** [HolographicWings/LethalExpansion#19]
I suppose it is due to the latest updates, because now the modified amount does not appear in the game

Here´s the config amount
![image](https://github.com/HolographicWings/LethalExpansion/assets/152836693/2f2305c4-03c8-4c0a-b86f-2260e2872da6)

The match itself
![image](https://github.com/HolographicWings/LethalExpansion/assets/152836693/3ece5155-5ad5-4ebb-971d-188fa0560731)

![image](https://github.com/HolographicWings/LethalExpansion/assets/152836693/c1984c21-ad90-45ef-a4f5-06478f847380)

**Comment by SrMoroxide** [comment]
Confirmed, the 1.2.6 version works perfectly
![image](https://github.com/HolographicWings/LethalExpansion/assets/152836693/032b26c4-5da9-43c2-9abe-bf17cd0ea2f1)

![image](https://github.com/HolographicWings/LethalExpansion/assets/152836693/2b0d386c-b428-4e2f-8e95-f59c733a4186)

**Comment by SrMoroxide** [comment]
And tested, since v1.2.7 the StartingCredits, StartingQuota options were broken

**Comment by Dragongas2003** [comment]
can confirm on having a similar issue

**Comment by HolographicWings** [comment]
Will try today
thanks you

**Comment by HolographicWings** [comment]
fixed in 1.2.10
