### ISSUE TITLE
The explanatory note interface for the bottom option could not be displayed

### ISSUE THREAD

**Issue by TShineCN** [HolographicWings/LethalExpansion#2]
First of all, thank you very much for creating such a high-quality mod. However, when I opened the mod menu, I found that the explanatory note interface for the bottom option could not be displayed, and the scroll bar could not be pulled down.I'm not sure if anyone else has encountered the same problem as me.

![问题](https://github.com/HolographicWings/LethalExpansion/assets/54096173/c05f19f5-c1ff-4acc-82ef-61bde4da71dc)

**Comment by HolographicWings** [comment]
ah yes that's true ^^ i forgot this issue, i will fix it in next updates
thanks you
here infos about the 3 last settings
![image](https://github.com/HolographicWings/LethalExpansion/assets/19623115/5d75da54-755e-4738-b222-aa0fe85bc491)

**Comment by HolographicWings** [comment]
> First of all, thank you very much for creating such a high-quality mod. However, when I opened the mod menu, I found that the explanatory note interface for the bottom option could not be displayed, and the scroll bar could not be pulled down.I'm not sure if anyone else has encountered the same problem as me.
> 
> ![问题](https://private-user-images.githubusercontent.com/54096173/289501104-c05f19f5-c1ff-4acc-82ef-61bde4da71dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzMDc2OTAsIm5iZiI6MTcwMjMwNzM5MCwicGF0aCI6Ii81NDA5NjE3My8yODk1MDExMDQtYzA1ZjE5ZjUtYzFmZi00YWNjLTgyZWYtNjFiZGU0ZGE3MWRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjExVDE1MDk1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0NTk3NjllYzljMWI2N2U1MDZiYTlhZmVmMWNkY2RlNTZlOGE4MGYyYzAwYWQ1MDNlOTM0NDg3NGRlZDRkNTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.F_CgpjFXVyMujDFRkfqPWFuD5sM5njSaZVIZZYRQ6K0)

ah yes that's true ^^ i forgot this issue, i will fix it in next updates
thanks you
here infos about the 3 last settings
![image](https://github.com/HolographicWings/LethalExpansion/assets/19623115/5d75da54-755e-4738-b222-aa0fe85bc491)

**Comment by HolographicWings** [comment]
This is done in 1.2.x

**Comment by TShineCN** [comment]
> This is done in 1.2.x

Thank you very much! I will recommend your mod to my friends, especially the new added map which is very fun
