### ISSUE TITLE
Coil heads on Wateridge only target host

### ISSUE THREAD

**Issue by virmust** [HolographicWings/LethalExpansion#20]
As per the title, only the host is targeted by Coil Heads on this map. All other maps, Coil Heads act normally.

**Comment by HolographicWings** [comment]
> As per the title, only the host is targeted by Coil Heads on this map. All other maps, Coil Heads act normally.

Interesting, could you made a video of this happen ?

**Comment by Dantoresco** [comment]
Just commenting as a data entry.
Same happened to me (no video, sadly)
Coil heads on Wateridge ignored everyone except the host and they could only be stopped if the host was looking at them

**Comment by DigitalIver** [comment]
this is sometime true sometime not brutal company plus "they are shy" event also cause this issue with both bracken and coilhead moving aimlessly in one direction and ignoring the players completely they seem it also broken with other player too. The coil head in this mod also have occur once with a few friend they ignoring me but doesn't ignoring the host or specific player.

**Comment by Dragongas2003** [comment]
can confirm that this was the case because the coilhead wasnt targeting me or my friend next to me in the building then my host came in and instantly died and the coil head went on his way. sadly didnt record it but next time me and my friends play ill try to record it to capture it

**Comment by Dragongas2003** [comment]
i would also like to note i wasnt using a event mod like brutal

**Comment by HolographicWings** [comment]
I experimented to be killed by the coil head on wateridge without being host yesterday, this is weird, i need a video as well
Did you experimented it when only LE was installed ?

**Comment by Dragongas2003** [comment]
whenever I get the chance ill try to get a video of it

**Comment by Sinpls** [comment]
Currently experiencing the same issue

**Comment by subz** [comment]
Coil-heads attacking only host on every modded map. They will walk around other players and will not stop moving until they find the host inside, once host dies to them they still continue to ignore everyone else.

**Comment by HolographicWings** [comment]
thanks you for theses reports, does any of you tried with only LE ?
i have no clue of what happening, any information as used mods, potential errors in logs that could be relevent, etc will help me to understand what is happening
@virmust @Dantoresco @DigitalIver @Dragongas2003 @Sinpls @subz

**Comment by Sinpls** [comment]
I've posted the my modlist and latest beplnX log below. If there could be any mod interfering I'd expect it to be either:

- MoreCompany (Since the other lobby mod currently does not work with lethal expansion)
- LateCompany (Related to lobby mod)
- ScalingStartCredits (since I believe LethalExpansion also has this as a configurable value, though I believe ScalingStartCredits did not work due to this)

I only played on modded moons so I can't verify whether is also happens on vanilla moons. I also did not check in isolation.
Beyond the issue in this thread I also encountered some desyncs with the mimic mod as well as people leaving but still being in the game. This caused an issue where I (host) had to die twice. This issue persisted over multiple runs so I had to restart the server.
Of course unsure whether anything is related.

**Latest log output:**
[LogOutput.log](https://github.com/HolographicWings/LethalExpansion/files/13808760/LogOutput.log)
LethalExpansion is throwing a lot of errors at the start, but unsure if they have anything to do with it.

**Modlist:**
BepInEx-BepInExPack-5.4.2100
2018-LC_API-3.2.3
anormaltwig-LateCompany-1.0.9
Renegades-FlashlightToggle-1.5.0
tinyhoot-ShipLoot-1.0.0
Renegades-WalkieUse-1.4.0
AlexCodesGames-AdditionalSuits-1.1.3
Giltong-LethalCompanyDRP-1.3.6
Thorlar-HealthStation-1.0.1
vasanex-ItemQuickSwitch-1.1.0
FlipMods-LetMeLookDown-1.0.1
Drakorle-MoreItems-1.0.1
FlipMods-ObjectVolumeController-1.0.3
FlipMods-FasterItemDropship-1.2.0
x753-Mimics-2.3.0
sunnobunno-YippeeMod-1.2.2
sunnobunno-BonkHitSFX-1.0.4
TheBeeTeam-PersistentPurchases-1.2.0
taffyko-NameplateTweaks-1.0.5
FlipMods-TooManyEmotes-1.5.10
HomelessGinger-MaskedEnemyOverhaul-2.1.0
RugbugRedfern-Skinwalkers-2.0.1
Evaisa-HookGenPatcher-0.0.5
Evaisa-LethalLib-0.10.1
Evaisa-LethalThings-0.8.8
PortableNavi-BetterInverseTeleporter-1.0.2
Rune580-LethalCompany_InputUtils-0.4.4
5Bit-VoiceHUD-1.0.4
no00ob-LCSoundTool-1.4.0
Clementinise-CustomSounds-2.2.0
HoffmanTV-angry_british_bug-1.4.1
FlipMods-BetterStamina-1.3.2
Hexnet111-SuitSaver-1.1.2
HolographicWings-LethalExpansion-1.3.11
sfDesat-Orion-1.1.0
matsuura-HealthMetrics-1.0.2
Vulf-GokuBracken-1.3.0
sunnobunno-ScalingStartCredits-1.0.1
x753-More_Suits-1.4.1
Verity-TooManySuits-1.0.4
happyfrosty-FrostySuits-1.1.7
QuFix-Lidl_Suit-1.0.3
Festive_Arms-FNAF_Suits-2.0.0
GorillaBeast-GorillaSuits-0.0.10
OnePeak-Low_Budget_One_Piece_suits-0.5.1
Park-Park_Suits-1.0.6
OE_Tweaks-Thumper_Chase_Music-1.0.2
EliteMasterEric-Coroner-1.5.3
SlushyRH-FreeeeeeMoooooons-1.0.1
Dafini-Dafis_Mega_Moon_Pack_Emporium-1.2.10
sfDesat-Aquatis-0.4.0
notnotnotswipez-MoreCompany-1.7.2
Team_Waluigi-WaluigiSuit-0.0.3

I did update in between posting my first comment and this one, so so mods have a different version compared to the outputlog.

**Comment by CmmmmmmLau** [comment]
same issue here, but base on my test. It onle happen on the custom moons. official moons is ok.

**Comment by 21Joakim** [comment]
I think I have tracked this down to an issue with `isInFactory` (in `PlayerControllerB`) not being synced between the player and server, the player enters the factory and thinks it's inside the factory but the server does not. When you manually set this to `true` on the server (with something like [UnityExplorer](https://github.com/sinai-dev/UnityExplorer)) it starts working again, I haven't figured out why it's not synced yet though

**Comment by HolographicWings** [comment]
> I think I have tracked this down to an issue with `isInsideFactory` (in `PlayerControllerB`) not being synced between the player and server, the player enters the factory and thinks it's inside the factory but the server does not. When you manually set this to `true` on the server (with something like [UnityExplorer](https://github.com/sinai-dev/UnityExplorer)) it starts working again, I haven't figured out why it's not synced yet though.
> 
> Also, from my testing the issue might be much worse than just coil-heads not acknowleding you (though it is the most obvious example), it seems like essentially every single AI inside the factory is affected by this

this may fix the thunder shooting inside too !
thanks you i will investigate on this value and why it doesn't apply

**Comment by HolographicWings** [comment]
> I think I have tracked this down to an issue with `isInsideFactory` (in `PlayerControllerB`) not being synced between the player and server, the player enters the factory and thinks it's inside the factory but the server does not. When you manually set this to `true` on the server (with something like [UnityExplorer](https://github.com/sinai-dev/UnityExplorer)) it starts working again, I haven't figured out why it's not synced yet though.
> 
> Also, from my testing the issue might be much worse than just coil-heads not acknowleding you (though it is the most obvious example), it seems like essentially every single AI inside the factory is affected by this

This may fix the thunder shooting inside too !
Thanks you.
The entrances have the proper settings to change this value i will investigate on this value and why it doesn't apply.
Did you noticed a light issue on the maps where the coilhead didn't triggered the players ? Like if the outside light came in dungeon.

**Comment by HolographicWings** [comment]
> I think I have tracked this down to an issue with `isInsideFactory` (in `PlayerControllerB`) not being synced between the player and server, the player enters the factory and thinks it's inside the factory but the server does not. When you manually set this to `true` on the server (with something like [UnityExplorer](https://github.com/sinai-dev/UnityExplorer)) it starts working again, I haven't figured out why it's not synced yet though.
> 
> Also, from my testing the issue might be much worse than just coil-heads not acknowleding you (though it is the most obvious example), it seems like essentially every single AI inside the factory is affected by this

This may fix the thunder shooting inside too !
Thanks you.
The entrances have the proper settings to change this value, i will investigate on it to find why doesn't apply.
Did you noticed a light issue on the maps where the coilhead didn't triggered the players ? Like if the outside light came in dungeon.

**Comment by 21Joakim** [comment]
> > I think I have tracked this down to an issue with `isInsideFactory` (in `PlayerControllerB`) not being synced between the player and server, the player enters the factory and thinks it's inside the factory but the server does not. When you manually set this to `true` on the server (with something like [UnityExplorer](https://github.com/sinai-dev/UnityExplorer)) it starts working again, I haven't figured out why it's not synced yet though.
> > Also, from my testing the issue might be much worse than just coil-heads not acknowleding you (though it is the most obvious example), it seems like essentially every single AI inside the factory is affected by this
> 
> This may fix the thunder shooting inside too ! Thanks you. The entrances have the proper settings to change this value, i will investigate on it to find why it doesn't apply. Did you noticed a light issue on the maps where the coilhead didn't triggered the players ? Like if the outside light came in dungeon.

Not that I noticed but the `isInsideFactory` value is properly set on the client so everything should look normal.

I investigated it a bit more and it seems like the issue probably has to do with the `GameObject` which contains the `EntranceTeleport` component not being networked properly, this is what it looks like for the client on a custom moon (on a normal moon it looks fine with all the proper values). Might be worth to mention that the `triggerScript` (in `EntranceTeleport`) is also set to null while normally it would be set to the `InteractTrigger` component in the same object
![image](https://github.com/HolographicWings/LethalExpansion/assets/11248267/8c58ab96-6366-4759-a12f-2ab4a164501b)

**Comment by HolographicWings** [comment]
> > > I think I have tracked this down to an issue with `isInsideFactory` (in `PlayerControllerB`) not being synced between the player and server, the player enters the factory and thinks it's inside the factory but the server does not. When you manually set this to `true` on the server (with something like [UnityExplorer](https://github.com/sinai-dev/UnityExplorer)) it starts working again, I haven't figured out why it's not synced yet though.
> > > Also, from my testing the issue might be much worse than just coil-heads not acknowleding you (though it is the most obvious example), it seems like essentially every single AI inside the factory is affected by this
> > 
> > This may fix the thunder shooting inside too ! Thanks you. The entrances have the proper settings to change this value, i will investigate on it to find why it doesn't apply. Did you noticed a light issue on the maps where the coilhead didn't triggered the players ? Like if the outside light came in dungeon.
> 
> Not that I noticed but the `isInsideFactory` value is properly set on the client so everything should look normal.
> 
> I investigated it a bit more and it seems like the issue probably has to do with the `GameObject` which contains the `EntranceTeleport` component not being networked properly, this is what it looks like for the client on a custom moon (on a normal moon it looks fine with all the proper values). Might be worth to mention that the `triggerScript` (in `EntranceTeleport`) is also set to null while normally it would be set to the `InteractTrigger` component in the same object
> ![image](https://github.com/HolographicWings/LethalExpansion/assets/11248267/8c58ab96-6366-4759-a12f-2ab4a164501b)

I think I know how to fix this
It's not sync because the moon is a prefab that gets Instanced 
There's another way to instance it

**Comment by HolographicWings** [comment]
@21Joakim should be fixed, will be released in next update

**Comment by 21Joakim** [comment]
> @21Joakim network should be fixed, will be released in next update we'll see if that fix the coilhead

Thank you for the quick fix!

I am guessing this only fixes it for your moons (seemed to work fine on Wateridge but not [Secret Labs](https://thunderstore.io/c/lethal-company/p/Zingar/SecretLabs/) where I first found the issue), what does a custom moon need to do to fix it?

Is there something that could be done to mitigate the issue for existing custom moons, like automatically updating the prefab of a custom moon if it contains the broken part?

**Comment by HolographicWings** [comment]
> > @21Joakim network should be fixed, will be released in next update we'll see if that fix the coilhead
> 
> Thank you for the quick fix!
> 
> I am guessing this only fixes it for your moons (seemed to work fine on Wateridge but not [Secret Labs](https://thunderstore.io/c/lethal-company/p/Zingar/SecretLabs/) where I first found the issue), what does a custom moon need to do to fix it?
> 
> Is there something that could be done to mitigate the issue for existing custom moons, like automatically updating the prefab of a custom moon if it contains the broken part?

but i didn't did any update yet ._.

**Comment by 21Joakim** [comment]
> but i didn't did any update yet ._.

You commited the changes, I assume that contains the fix? 😅

**Comment by HolographicWings** [comment]
> > but i didn't did any update yet ._.
> 
> You commited the changes, I assume that contains the fix? 😅 

Ooh
Yes that's true x)
If you want to build it to test you can
But I don't want to release it yet with only this commit

**Comment by 21Joakim** [comment]
After testing it again it appears the fire exit entrances do not work properly, they all take you to the main entrance

**Comment by HolographicWings** [comment]
> After testing it again it appears the fire exit entrances do not work properly, they all take you to the main entrance

Ah yes, stupid mistake, now i instantiate the entrance from a prefab registered on network, so it's always ID 0

**Comment by HolographicWings** [comment]
i had to reverse the change, as the entrances was not instanced with the network manager, it was keeping it's default ID for some reasons, i don't understand unity networking very well
changing the value on host then spawning the entrances didn't fixed it, the clients still had ID 0 for every entrances

**Comment by 21Joakim** [comment]
I made a fix for LethalExpansionCore (https://github.com/LethalMods/LethalExpansionCore/commit/550c2b28c36d1cf88721e063c54ca994f3b41b84) but it relies on the `NetworkObject` being present, seemingly it was still removed from waterridge after you reverted the change and the Christmas moon now seems to have all entrance ids set to 0

**Comment by HolographicWings** [comment]
should be fixed since almost one month, closing the issue
