### ISSUE TITLE
Items changing on reload

### ISSUE THREAD

**Issue by Konoha9** [HolographicWings/LethalExpansion#21]
Seems items from this or using this to spawn change into items from lethal things Link: https://thunderstore.io/c/lethal-company/p/Evaisa/LethalThings/ And sadly they are both great mods would love if they could work together

**Comment by HolographicWings** [comment]
i will talk with avaisa at some point to work together on a compatibility between our mods

**Comment by HolographicWings** [comment]
> Seems items from this or using this to spawn change into items from lethal things Link: https://thunderstore.io/c/lethal-company/p/Evaisa/LethalThings/ And sadly they are both great mods would love if they could work together

Hello
I will work on this the next week
Could you tell me more about what is happening?

**Comment by HolographicWings** [comment]
@Konoha9 
Hello
I will work on this the next week
Could you tell me more about what is happening?

**Comment by HolographicWings** [comment]
no answer, i close the issue.
