### ISSUE TITLE
Unable to play multiplayer with previous save files.

### ISSUE THREAD

**Issue by GoliathX211** [HolographicWings/LethalExpansion#22]
Getting errors such as "An error occured" and "An error occured while spawning into the game. Please report the glitch!"
We can typically start lobbies and play on new saves but as soon as we get done with our session and try to come back to the save, it gives us an error. We played on Wateridge as well as the vanilla maps.
We have been having this issue since we installed the mod around version 1.2.5

**Comment by HolographicWings** [comment]
> Getting errors such as "An error occured" and "An error occured while spawning into the game. Please report the glitch!" We can typically start lobbies and play on new saves but as soon as we get done with our session and try to come back to the save, it gives us an error. We played on Wateridge as well as the vanilla maps. We have been having this issue since we installed the mod around version 1.2.5

i need logs please

**Comment by GoliathX211** [comment]
I will get those to you as soon as my friend gets online and we should be able to give you both client and host logs.

**Comment by GoliathX211** [comment]
[LogOutput (Host).log](https://github.com/HolographicWings/LethalExpansion/files/13695477/LogOutput.Host.log)
[LogOutput (Guest).log](https://github.com/HolographicWings/LethalExpansion/files/13695478/LogOutput.Guest.log)
When trying experimentation, we were able to load up the save and join just fine. As soon as we tried Wateridge, the problem started occuring again.
We are using the latest version 1.2.11 while testing.

**Comment by GoliathX211** [comment]
The host of the save visited Experimentation directly after that test, went back to the main menu and reloaded the save.
I was able to join. This seems to be a problem with the custom maps. (Orion did the same thing to us previously)

**Comment by HolographicWings** [comment]
[Info   : Unity Log] level id: 10
[Info   : Unity Log] Changing level
[Error  : Unity Log] Failed to assign new player with client id #3: System.IndexOutOfRangeException: Index was outside the bounds of the array.
  at StartOfRound.ChangeLevel (System.Int32 levelID) [0x0001f] in <44743d9474784365a095189c76175301>:0 
  at (wrapper dynamic-method) StartOfRound.DMD<StartOfRound::OnPlayerConnectedClientRpc>(StartOfRound,ulong,int,ulong[],int,int,int,int,int,int,int)

do you have exactly same setup host and client ?

**Comment by GoliathX211** [comment]
They should. We export the profile on r2modman as a code and send it that way. After we updated a ton of mods, the configs got reset anyway and we haven't altered them since.

**Comment by HolographicWings** [comment]
Ah yes my bad @GoliathX211 
When someone join you while you are already on a new moon, it will show this error because the new moons are added to the list after joined the lobby, theres no other way to do it
So stay on a vanilla moon before inviting peoples

**Comment by HolographicWings** [comment]
@GoliathX211 let me know if fixed

**Comment by GoliathX211** [comment]
The issue is fixed on the latest version. Thank you so much.
