### ISSUE TITLE
Mod settings doesnt open

### ISSUE THREAD

**Issue by LuciferEOS** [HolographicWings/LethalExpansion#23]
when im pressing on mod settings its opening just game settings, and i cant change deadline and other stuff, here's the log
[LogOutput.log](https://github.com/HolographicWings/LethalExpansion/files/13692856/LogOutput.log)

**Comment by LuciferEOS** [comment]
![изображение](https://github.com/HolographicWings/LethalExpansion/assets/154002422/e964425a-bee2-4376-ab3e-7e7631c62a2c)
and there is another bug, when i choose mod settings its choosing mod setting AND norman settings too! i dont know if its only my game or is it on every computer

**Comment by HolographicWings** [comment]
> when im pressing on mod settings its opening just game settings, and i cant change deadline and other stuff, here's the log [LogOutput.log](https://github.com/HolographicWings/LethalExpansion/files/13692856/LogOutput.log)


[Error  : Unity Log] Unable to open archive file: C:/Users/Admin/Desktop/Lethal Company/BepInEx/plugins/lethalexpansion.lem
[Error  : Unity Log] Failed to read data for the AssetBundle 'C:\Users\Admin\Desktop\Lethal Company\BepInEx\plugins\lethalexpansion.lem'.

this file failed to load

**Comment by nesia7** [comment]
same thing is happening to me, if holo sees this could you add instructions to download cause im lost.

**Comment by nesia7** [comment]
yo quick upd, i think you installed wrong, put all dat file stuff into the "plugins," i put in the LEM files and the .dll's and the mod settins open and i get all my planets and mods.

**Comment by HolographicWings** [comment]
> yo quick upd, i think you installed wrong, put all dat file stuff into the "plugins," i put in the LEM files and the .dll's and the mod settins open and i get all my planets and mods.

The new menu is in the LethalExpansion.lem yes

**Comment by K1sk3** [comment]
> yo quick upd, i think you installed wrong, put all dat file stuff into the "plugins," i put in the LEM files and the .dll's and the mod settins open and i get all my planets and mods.

bro what??? could u explain how did u do that? i just cant download that....dont understand

**Comment by HolographicWings** [comment]
> > yo quick upd, i think you installed wrong, put all dat file stuff into the "plugins," i put in the LEM files and the .dll's and the mod settins open and i get all my planets and mods.
> 
> bro what??? could u explain how did u do that? i just cant download that....dont understand 

Use r2modman to install it if you struggle with manual installation
