### ISSUE TITLE
Friends kicked from lobby despite having LethalExpansion Installed

### ISSUE THREAD

**Issue by samsterpiece** [HolographicWings/LethalExpansion#24]
I am wondering what is going on with how whenever someone joins, they get kicked from the lobby right away despite mod list showing me they have lethal expansion. 
![image](https://github.com/HolographicWings/LethalExpansion/assets/50347830/c58978ea-0b5e-4b22-b71b-62c66c331e07)
[LogOutput.log](https://github.com/HolographicWings/LethalExpansion/files/13693202/LogOutput.log)

**Comment by samsterpiece** [comment]
```
[Error  :  HarmonyX] Error while running static void LateCompany.Patches.ConnectionApproval_Patch::Postfix(Unity.Netcode.NetworkManager+ConnectionApprovalRequest request, Unity.Netcode.NetworkManager+ConnectionApprovalResponse response). Error: System.NullReferenceException: Object reference not set to an instance of an object
  at LateCompany.Patches.ConnectionApproval_Patch.Postfix (Unity.Netcode.NetworkManager+ConnectionApprovalRequest request, Unity.Netcode.NetworkManager+ConnectionApprovalResponse response) [0x00019] in <81650565a1b7418ca57e5306acf7a29f>:0 
  at (wrapper dynamic-method) GameNetworkManager.DMD<GameNetworkManager::ConnectionApproval>(GameNetworkManager,Unity.Netcode.NetworkManager/ConnectionApprovalRequest,Unity.Netcode.NetworkManager/ConnectionApprovalResponse)
[Info   : Unity Log] [Netcode] [Server-Side Client-Synchronization] NetworkObject serialization order:ChangableSuit(Clone)LocalItemHolderServerItemHolderExtraPlayer15PlayerPhysicsBoxLocalItemHolderServerItemHolderExtraPlayer14PlayerPhysicsBoxLocalItemHolderServerItemHolderExtraPlayer13PlayerPhysicsBoxLocalItemHolderServerItemHolderExtraPlayer12PlayerPhysicsBoxLocalItemHolderServerItemHolderExtraPlayer11PlayerPhysicsBoxLocalItemHolderServerItemHolderRoundManagerPlayerPhysicsBoxExtraPlayer4ServerItemHolderExtraPlayer9PlayerPhysicsBoxLocalItemHolderServerItemHolderExtraPlayer8PlayerPhysicsBoxLocalItemHolderServerItemHolderExtraPlayer7PlayerPhysicsBoxLocalItemHolderServerItemHolderExtraPlayer6PlayerPhysicsBoxLocalItemHolderServerItemHolderExtraPlayer5PlayerPhysicsBoxLocalItemHolderServerItemHolderExtraPlayer10PlayerPhysicsBoxPlayersManager / HUDManagerPlayerPropsHangarShipPlayer (1)ChangableSuit(Clone)ChangableSuit(Clone)ChangableSuit(Clone)ChangableSuit(Clone)ChangableSuit(Clone)ChangableSuit(Clone)ChangableSuit(Clone)ChangableSuit(Clone)ChangableSuit(Clone)ChangableSuit(Clone)ChangableSuit(Clone)ChangableSuit(Clone)ChangableSuit(Clone)ChangableSuit(Clone)ChangableSuit(Clone)ChangableSuit(Clone)ChangableSuit(Clone)EnvironmentStorageClosetServerItemHolderStartGameLeverBunkbedsLocalItemHolderLocalItemHolderLocalItemHolderLocalItemHolderPlayerPhysicsBoxPlayerPhysicsBoxPlayerPhysicsBoxTerminalServerItemHolderServerItemHolderServerItemHolderStickyNoteItemClipboardManualPlayerPhysicsBoxShipBuildModeFileCabinetGlobalEffectsSoundManagerLightSwitchContainerTimeAndWeatherPlayer (3)Player (2)LocalItemHolder
```

Here is newest log 
[LogOutput.log](https://github.com/HolographicWings/LethalExpansion/files/13693206/LogOutput.log)

**Comment by HolographicWings** [comment]
> I am wondering what is going on with how whenever someone joins, they get kicked from the lobby right away despite mod list showing me they have lethal expansion. ![image](https://private-user-images.githubusercontent.com/50347830/291004791-c58978ea-0b5e-4b22-b71b-62c66c331e07.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI3NDgxMzYsIm5iZiI6MTcwMjc0NzgzNiwicGF0aCI6Ii81MDM0NzgzMC8yOTEwMDQ3OTEtYzU4OTc4ZWEtMGI1ZS00YjIyLWI3MWItNjJjNjZjMzMxZTA3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE2VDE3MzAzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwZTc5YmMxNmUwMGU3YWQxMjQ5YjA5ZjBiMDNiOTBkZDkwNzJkNzFkZTJmNzVkNzkzZDc4ZjkwMmNhYWUzNDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1dCkbUFYE1v8t9fqkOxZnK_9ZA_XjBvh94UWvBJVU70) [LogOutput.log](https://github.com/HolographicWings/LethalExpansion/files/13693202/LogOutput.log)

This screenshot show an incompatibility between LE and another mod

**Comment by DigitalIver** [comment]
I don't think there any issue like this happen to the module the only module seem to kick player despite they still have the same mod is lc_api and you have to enable some config for that module in order their friend to join without getting kicked. I think this issue is no longer need further information

**Comment by HolographicWings** [comment]
@samsterpiece you should try yes

**Comment by HolographicWings** [comment]
no answer, i close the issue.
