### ISSUE TITLE
Readme missing install steps/guide

### ISSUE THREAD

**Issue by SHSHYLO** [HolographicWings/LethalExpansion#26]
No idea where to put the Modules folder, the sdk dll, mod dll, and the .lem. I don't use mod managers.

**Comment by SHSHYLO** [comment]
For now i will just guess

**Comment by HolographicWings** [comment]
> No idea where to put the Modules folder, the sdk dll, mod dll, and the .lem. I don't use mod managers.

Well, anywhere in the plugins folder as absolutely any mod
They just must be together, in same folder is recommended

**Comment by SHSHYLO** [comment]
> > No idea where to put the Modules folder, the sdk dll, mod dll, and the .lem. I don't use mod managers.
> 
> Well, anywhere in the plugins folder as absolutely any mod They just must be together, in same folder is recommended

oh sweet thank for the quick reply I love the fuck outta you, assumed it might be a little different than other mods.
