### ISSUE TITLE
People Loading in different seeds

### ISSUE THREAD

**Issue by DrouDrougar** [HolographicWings/LethalExpansion#27]
So we might be running to many mods at the same time, And sadly i was never the one having the issues. But we had people in different seeds of the map.

Example: different layout of staircases. could walk trough doors that were not there for the rest of us. 
Could drown because for him the world was flooded, while for us it was normal, he was host at one point and the world was eclipsed for him but for us it was normal... We got eaten when we landed by dogs.

ima throw my logoutput and you can try to find something in there. maybe it helps maybe it does not.. Alot of fart cushin calls.

[LogOutput.zip](https://github.com/HolographicWings/LethalExpansion/files/13694363/LogOutput.zip)

im not sure if the logs are reset between sessions so maybe it wont help you at all. otherwise yeah we were in the middle of playing so i had no time i just reset the mod pack we ran to a version without the lethalexpansion.

Tell me if you need something more from me and i can see what i can do.

**Comment by DigitalIver** [comment]
i have the same problem except it target only 1 specific players

**Comment by HolographicWings** [comment]
> i have the same problem except it target only 1 specific players

did you noticed a different seed displayed at the loading ?

**Comment by HolographicWings** [comment]
@DigitalIver @DrouDrougar 
did you noticed a different seed displayed at the loading ?
btw your log file display 89470 times the word error, you should begin to clean your modpack

**Comment by DigitalIver** [comment]
Is lethal escape compatible with this mod if it is i don't think any other mods can cause this type of desync

**Comment by HolographicWings** [comment]
> Is lethal escape compatible with this mod if it is i don't think any other mods can cause this type of desync

I really dunno.. i fail to pinpoint the origin of the problem

**Comment by DrouDrougar** [comment]
yeah i don't know, and alot of the errors is because of small things that i think we have mostly fixed. Like there is one error that is  because of an audifile that i have no idea where i should place it. Because it does not tell me where it needs to go. Cause some devs just do a hard required it to be in a specific folder, and then just place the audio file or image file in the open instead of in that specific folder. 

And the seed i don't know exactly because i was not the one suffering the error, it happened to two people this time around, and since they deleted their log files when they replaced the mod packs i can't even send you that, i could clear out the log file, install the thing and test around and see if we could replicate for you?

**Comment by HolographicWings** [comment]
@DrouDrougar @DigitalIver let me know if upcoming 1.2.14 fix the desync

**Comment by DigitalIver** [comment]
less go hopefully it finally fix
