### ISSUE TITLE
Hide TestMoon from the terminal

### ISSUE THREAD

**Issue by boomboompower** [HolographicWings/LethalExpansion#28]
I'm converting this comment from a previous issue on the Orion mod to this repository 

https://github.com/sfDesat/Orion/issues/4#issuecomment-1852096866

I think "TestMoon" should be hidden in the terminal by default (but maybe still possible to travel to if you put the word in?)

If this has already been done, please disregard this issue - thank you

**Comment by HolographicWings** [comment]
> I'm converting this comment from a previous issue on the Orion mod to this repository
> 
> [sfDesat/Orion#4 (comment)](https://github.com/sfDesat/Orion/issues/4#issuecomment-1852096866)
> 
> I think "TestMoon" should be hidden in the terminal by default (but maybe still possible to travel to if you put the word in?)
> 
> If this has already been done, please disregard this issue - thank you

But this is done since several days ^^" do your update the mod ?
