### ISSUE TITLE
Update checker is incredibly intrusive. 

### ISSUE THREAD

**Issue by subzerohurley** [HolographicWings/LethalExpansion#29]
I don't mean to sound rude but can we have the option to disable this? or just remove this feature? 
it's been broken for 3-4 updates now and get's stuck in the screen, pulling up the mouse with ESC hides the window only for it to pop back up when you unpause. I would update but in the past, that's had bad repercussions updating while making mods in the SDK. 
Plus there's been a few times where certain updates were broke. 
What i'm getting at is if people are on an old version, they're probably on it on purpose as there's already a layer of update checker via the mod managers so this adds a layer of redundancy and jank. 
I get the idea is that it SHOULD only show in the main menu, but after 3-4 updates of it not being fixed, it's better off to remove it for now imo, right?
![image](https://github.com/HolographicWings/LethalExpansion/assets/18029175/cd306b9c-176b-4762-a1cc-f67e1286a189)

**Comment by HolographicWings** [comment]
> I don't mean to sound rude but can we have the option to disable this? or just remove this feature? it's been broken for 3-4 updates now and get's stuck in the screen, pulling up the mouse with ESC hides the window only for it to pop back up when you unpause. I would update but in the past, that's had bad repercussions updating while making mods in the SDK. Plus there's been a few times where certain updates were broke. What i'm getting at is if people are on an old version, they're probably on it on purpose as there's already a layer of update checker via the mod managers so this adds a layer of redundancy and jank. I get the idea is that it SHOULD only show in the main menu, but after 3-4 updates of it not being fixed, it's better off to remove it for now imo, right? ![image](https://private-user-images.githubusercontent.com/18029175/291069004-cd306b9c-176b-4762-a1cc-f67e1286a189.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4MjYwNjAsIm5iZiI6MTcwMjgyNTc2MCwicGF0aCI6Ii8xODAyOTE3NS8yOTEwNjkwMDQtY2QzMDZiOWMtMTc2Yi00NzYyLWExY2MtZjY3ZTEyODZhMTg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE3VDE1MDkyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNhNDFlNDRjZjIwNDZkYzBkNjU4MmJjOTBjMjU2MDM3NGYxMTg5YjFhNzdmMGY0MzhiMzg0MzI0M2ZiZDRkNzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zqugUg2oj3AjQmuR4KgTqVqU2G1pcuGgR10caG5DtHk)

This window is not supposed to appear outside of the main menu
Why the fuck it appear in game ?????

**Comment by HolographicWings** [comment]
> I don't mean to sound rude but can we have the option to disable this? or just remove this feature? it's been broken for 3-4 updates now and get's stuck in the screen, pulling up the mouse with ESC hides the window only for it to pop back up when you unpause. I would update but in the past, that's had bad repercussions updating while making mods in the SDK. Plus there's been a few times where certain updates were broke. What i'm getting at is if people are on an old version, they're probably on it on purpose as there's already a layer of update checker via the mod managers so this adds a layer of redundancy and jank. I get the idea is that it SHOULD only show in the main menu, but after 3-4 updates of it not being fixed, it's better off to remove it for now imo, right?

Why the fuck it appear in game ?????

**Comment by subzerohurley** [comment]
I honestly wish i knew, only mod i have that remotely changes the menu is MoreCompany, maybe that's it?
