### ISSUE TITLE
Custom moons wont load

### ISSUE THREAD

**Issue by Ptitenana** [HolographicWings/LethalExpansion#3]
im trying to test the sea port moon and orion moon but it wont load i dont know if i installed it incorrectly

**Comment by HolographicWings** [comment]
> im trying to test the sea port moon and orion moon but it wont load i dont know if i installed it incorrectly

hello
i need more informations, i can't help you with that only one sentence
i need logs, video, screenshots, anything that could be relevant

did you updated the two mods ?

**Comment by Ptitenana** [comment]
What file do i put modules and the lethalexpansion lem file?

**Comment by HolographicWings** [comment]
> What file do i put modules and the lethalexpansion lem file?

i don't understand your sentence ;-;
the mods in their default setup must work if they are up to date
if theres anything red in the logs, send me it

**Comment by Ptitenana** [comment]
![scren](https://github.com/HolographicWings/LethalExpansion/assets/153454942/4b3b5145-e1a9-4788-b1ad-36c12df26a50)
heres a screenshot

**Comment by Ptitenana** [comment]
![temin](https://github.com/HolographicWings/LethalExpansion/assets/153454942/098da7b7-8d25-45a5-9914-55c88f3bfcc8)

**Comment by HolographicWings** [comment]
i just noticed in the log you sent, only lethalexpansion.lem is in your game
did you removed the other modules ?

**Comment by HolographicWings** [comment]
> i got it to work i thought i was ment to put the modules in bundles thanks for the help

the modules can be anywhere in the plugins folder, when you install the mod it's supposed to be done by default 🤔
