### ISSUE TITLE
The ESC Button on Terminal dont have a function

### ISSUE THREAD

**Issue by Snaetsh** [HolographicWings/LethalExpansion#30]
Please make it possible to presh ESC on the terminal - at this time we cant do that a freeze/stuck in terminal menu

**Comment by HolographicWings** [comment]
> Please make it possible to presh ESC on the terminal - at this time we cant do that a freeze/stuck in terminal menu

i don't understand, ESC already leaves the terminal

**Comment by Snaetsh** [comment]
All right. I will try our modlist. Idk if it that mod exactly

**Comment by Snaetsh** [comment]
Issue can be closed
