### ISSUE TITLE
Mod settins wont open

### ISSUE THREAD

**Issue by nesia7** [HolographicWings/LethalExpansion#31]
I open up the game, it shows the mod name on the bottom, i add another mod later, it works, (its on the newest ver.) everything works **BUT** opening the mod settings so i can do crap.

**Comment by nesia7** [comment]
[Info   : Unity Log] [FacepunchTransport] - Initialized access to Steam Relay Network.
[Info   : Unity Log] [FacepunchTransport] - Fetched user Steam ID.
[Info   :LethalExpansion] Unloading scene: InitScene
[Info   : Unity Log] Set version num
[Info   :LethalExpansion] Loading scene: MainMenu
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
LethalExpansion.Utils.HUD.SettingsMenu.InitSettingsMenu () (at <92ac49abf1344651bee2cbcafb92ea38>:0)
LethalExpansion.LethalExpansion.OnSceneLoaded (UnityEngine.SceneManagement.Scene scene, UnityEngine.SceneManagement.LoadSceneMode mode) (at <92ac49abf1344651bee2cbcafb92ea38>:0)
UnityEngine.SceneManagement.SceneManager.Internal_SceneLoaded (UnityEngine.SceneManagement.Scene scene, UnityEngine.SceneManagement.LoadSceneMode mode) (at <e27997765c1848b09d8073e5d642717a>:0)

this is the code i get when i open the "mod settings"

**Comment by nesia7** [comment]
sorry, i found out how to.

**Comment by HolographicWings** [comment]
> sorry, i found out how to.

Well, explain me if you found
Other people's may have the same issue
