### ISSUE TITLE
Lethal Expansion Added Custom scrap Desync Issue

### ISSUE THREAD

**Issue by DigitalIver** [HolographicWings/LethalExpansion#34]
I encounter another common desync problem is sometime that when someone pick up a custom added scrap that required Lethal expansion the scrap just stay there for other players and when they try to pick it up, the game create a huge lag spike or just do nothing except changing your weight a split second and just drop back down. scrap only fix when in the ship after orbit.

**Comment by DigitalIver** [comment]
so far the scrap that got the desync issue is : the golden cheese from Tokucade Scrap, The Molten Pig from PlushiesPlus, The Gold Ingots from AllTheScrap and one of the plushies from FrierenPlush. there probally more because it sometime happen. the scrap still behave normally though, but it leave back a fake decoy that other player cannot pickup which is sometime annoying.

**Comment by HolographicWings** [comment]
> so far the scrap that got the desync issue is : the golden cheese from Tokucade Scrap, The Molten Pig from PlushiesPlus, The Gold Ingots from AllTheScrap and one of the plushies from FrierenPlush. there probally more because it sometime happen. the scrap still behave normally though, but it leave back a fake decoy that other player cannot pickup which is sometime annoying.

Can you show me the logs ? Especially the part where the scraps are registered

**Comment by DigitalIver** [comment]
hmm i try to send a log when that occur again

**Comment by Konoha9** [comment]
It seems theres desync issues with any mods that add items or scrap not as a module for this like on game reload all sorts of stuff gets changed also

**Comment by DigitalIver** [comment]
here it happen again when i test with one of my friend 
[LogOutput.log](https://github.com/HolographicWings/LethalExpansion/files/13715318/LogOutput.log)

**Comment by DigitalIver** [comment]
also when you picking up some of those fake decoy scrap it also duplicated your weight too 
<img width="1280" alt="image" src="https://github.com/HolographicWings/LethalExpansion/assets/153030687/bc04d608-2329-4994-b890-88e83e6b67da">

**Comment by DigitalIver** [comment]
A video one how the issue work https://cdn.discordapp.com/attachments/1146000550475878471/1186638017423740928/Clip_-_12192023_104440_PM.mp4?ex=6593f9c6&is=658184c6&hm=f8b779e3b43a59a37e0125eb99565a21f1135cf9959096bc0f663f4212bf57ab&

**Comment by HolographicWings** [comment]
> It seems theres desync issues with any mods that add items or scrap not as a module for this like on game reload all sorts of stuff gets changed also

this is totally normal, if you add an element in a list the result of a random pickup with same seed will change

**Comment by HolographicWings** [comment]
> here it happen again when i test with one of my friend [LogOutput.log](https://github.com/HolographicWings/LethalExpansion/files/13715318/LogOutput.log)


[Error  : Unity Log] NetworkPrefab (mamamoosup) has a duplicate GlobalObjectIdHash source entry value of: 3298215809!

duplicated scrap i think
all i can do is add warnings for people who use the SDK when they missed a component but i can't fix
the issue come from on of the modules
the best you can do is try each module one by one till find which one is causing this issue

**Comment by Konoha9** [comment]
> > It seems theres desync issues with any mods that add items or scrap not as a module for this like on game reload all sorts of stuff gets changed also
> 
> this is totally normal, if you add an element in a list the result of a random pickup with same seed will change

Awww so theres no fix?

**Comment by HolographicWings** [comment]
> > > It seems theres desync issues with any mods that add items or scrap not as a module for this like on game reload all sorts of stuff gets changed also
> > 
> > 
> > this is totally normal, if you add an element in a list the result of a random pickup with same seed will change
> 
> Awww so theres no fix?

it's mathematics
i can't fix mathematics ^^"

**Comment by DigitalIver** [comment]
also video to see how it work

**Comment by DigitalIver** [comment]
also video to see how the issue work 

https://github.com/HolographicWings/LethalExpansion/assets/153030687/17a828f1-75fd-450f-94e4-3f4c25e67440

**Comment by DigitalIver** [comment]
> > > > It seems theres desync issues with any mods that add items or scrap not as a module for this like on game reload all sorts of stuff gets changed also
> > > 
> > > 
> > > this is totally normal, if you add an element in a list the result of a random pickup with same seed will change
> > 
> > 
> > Awww so theres no fix?
> 
> it's mathematics i can't fix mathematics ^^" i try to make the host check what modules the clients have to kick them if theres a mismatch but it's why you must play with peoples with exactly same mods as you

oh

**Comment by HolographicWings** [comment]
> also video to see how the issue work
> 
>  Video_2.mp4

i saw the video first time and answered you what to do

> > here it happen again when i test with one of my friend [LogOutput.log](https://github.com/HolographicWings/LethalExpansion/files/13715318/LogOutput.log)
> 
> [Error : Unity Log] NetworkPrefab (mamamoosup) has a duplicate GlobalObjectIdHash source entry value of: 3298215809!
> 
> duplicated scrap i think all i can do is add warnings for people who use the SDK when they missed a component but i can't fix the issue come from on of the modules the best you can do is try each module one by one till find which one is causing this issue

**Comment by DigitalIver** [comment]
also don't close this issue i try to find other modder that link to this issue too

**Comment by HolographicWings** [comment]
next SDK update will add a lot of warning when it find an anomaly

**Comment by DigitalIver** [comment]
that will be very helpful

**Comment by DigitalIver** [comment]
look like it not just happen with added custom scrap 
[LogOutput.log](https://github.com/HolographicWings/LethalExpansion/files/13724097/LogOutput.log)

**Comment by DigitalIver** [comment]
it also happen with a walkie talkie and a spray can

**Comment by DigitalIver** [comment]
wait it doesn't appear in the log but it appear on the game engine log

**Comment by HolographicWings** [comment]
> it also happen with a walkie talkie and a spray can

does it happen with only LE ?
the prior to know is if it's an issue from LE itself or a compatibility issue

**Comment by DigitalIver** [comment]
I have try added scrap that doesn't required LE and the scrap work normally i think doesn't get this issue for a while but it could be also a custom scrap mods cause this issue too i am currently suspecting lootable music tape mods one that cause this issue, but wouldn't too sure about it, may have to test all custom scrap that required lethal expansion too, but without that lootable music tape mods one to see if it fix the issue.

**Comment by DigitalIver** [comment]
Alright i just test the game again with my friend and look like the scrap desync issue thing is not happening to us anymore except it still happen sometime when a player pick up a flashlight or walkie talkie they still on the ground for the other player and they can't pick them up but it easy to fix by making the one that pick them up drop the flashlight and walkietalkie now other player can pick them up and it fix again, yea pretty happy with how the scrap workout for now, except there still some issue with alot moons like : lag, bad optimize in some moons, weather still active inside building in some moon and lot of unfinished stuff for now hope everything keep getting better.

**Comment by HolographicWings** [comment]
> Alright i just test the game again with my friend and look like the scrap desync issue thing is not happening to us anymore except it still happen sometime when a player pick up a flashlight or walkie talkie they still on the ground for the other player and they can't pick them up but it easy to fix by making the one that pick them up drop the flashlight and walkietalkie now other player can pick them up and it fix again, yea pretty happy with how the scrap workout for now, except there still some issue with alot moons like : lag, bad optimize in some moons, weather still active inside building in some moon and lot of unfinished stuff for now hope everything keep getting better.

LE don't interact with already existing scraps or buyable objects as flashlights
Weather in building have an official fix that every modder must fix
Does it happen in Wateridge and Christmas ?

**Comment by DigitalIver** [comment]
hmm i don't think it happen in wateridge and christmas only other unfinish moons

**Comment by DigitalIver** [comment]
so i guess this issue don't have to investigate any further ?

**Comment by DigitalIver** [comment]
might as well just close it

**Comment by HolographicWings** [comment]
Yes, the mappers must do that
![image](https://github.com/HolographicWings/LethalExpansion/assets/19623115/857bb291-7082-4716-9ffd-03e27565a0c8)
