### ISSUE TITLE
2 water ridge on moons catalogue

### ISSUE THREAD

**Issue by DigitalIver** [HolographicWings/LethalExpansion#38]
<img width="960" alt="image" src="https://github.com/HolographicWings/LethalExpansion/assets/153030687/b4566812-32de-4920-ba17-28b6423b3f2a"> are both different or the same ?

**Comment by HolographicWings** [comment]
> <img width="960" alt="image" src="https://github.com/HolographicWings/LethalExpansion/assets/153030687/b4566812-32de-4920-ba17-28b6423b3f2a"> are both different or the same ?

Wth ?
Logs please

**Comment by DigitalIver** [comment]
um how to post logs ?

**Comment by DigitalIver** [comment]
am i just gonna copy and paste the entire logs here ?

**Comment by HolographicWings** [comment]
I written a guide on the mod page for logs

**Comment by DigitalIver** [comment]
[LogOutput.log](https://github.com/HolographicWings/LethalExpansion/files/13713794/LogOutput.log)

**Comment by HolographicWings** [comment]
Thanks
I'll look at it in one or two hours I'm busy rn

**Comment by DigitalIver** [comment]
ok

**Comment by HolographicWings** [comment]
@DigitalIver 
[Error  :LethalExpansion] The given key 'Battery' was not present in the dictionary.
[Error  :LethalExpansion] The given key 'CannedFood' was not present in the dictionary.
[Error  :LethalExpansion] The given key 'Matchbox' was not present in the dictionary.
[Error  :LethalExpansion] The given key 'Pills' was not present in the dictionary.
[Error  :LethalExpansion] The given key 'Tape' was not present in the dictionary.
[Info   :LethalExpansion] Wateridge Moon added.
[Error  :LethalExpansion] The given key 'Battery' was not present in the dictionary.
[Error  :LethalExpansion] The given key 'CannedFood' was not present in the dictionary.
[Error  :LethalExpansion] The given key 'Matchbox' was not present in the dictionary.
[Error  :LethalExpansion] The given key 'Pills' was not present in the dictionary.
[Error  :LethalExpansion] The given key 'Tape' was not present in the dictionary.
[Info   :LethalExpansion] Orion Moon added.
[Error  :LethalExpansion] The given key 'Battery' was not present in the dictionary.
[Error  :LethalExpansion] The given key 'CannedFood' was not present in the dictionary.
[Error  :LethalExpansion] The given key 'Matchbox' was not present in the dictionary.
[Error  :LethalExpansion] The given key 'Pills' was not present in the dictionary.
[Error  :LethalExpansion] The given key 'Tape' was not present in the dictionary.
[Error  :LethalExpansion] The given key 'Blahaj' was not present in the dictionary.
[Error  :LethalExpansion] The given key 'Marmor' was not present in the dictionary.
[Info   :LethalExpansion] Wateridge Moon added.

one of your modules is adding another copy of Wateridge
try to disable them one by one till find which one is duplicating it

**Comment by DigitalIver** [comment]
hmm i check

**Comment by HolographicWings** [comment]
i try to avoid this anomaly to happen again for next update

**Comment by DigitalIver** [comment]
ah i fix it just doing a reinstall and it work
