### ISSUE TITLE
Game doesn't register some custom scrap and disappear

### ISSUE THREAD

**Issue by DigitalIver** [HolographicWings/LethalExpansion#39]
I was getting 2 bear plush from Plushies plus mod, a bronze trophy, Oj gloves and that 2 handed bronze statue thing from all the scrap, when i start the ship to orbit the moons, the game result screen ignore these scrap value and only count other scrap that is not from these mods the value it shown is 182$, scanning them still saying they still there and worth over 400$. and when i leave and 
rehost the save file, all the scrap that was not register by the game disappear and when i scan again the total value is now exactly 182$ just like the game show on the result screen. Kinda weird because all of these custom scrap required lethal expansion.

**Comment by DigitalIver** [comment]
i was playing solo with this one

**Comment by HolographicWings** [comment]
The module is not from me, all what i can do it add a lot of warnings in the SDK when an anomaly is found, but i can't fix the scraps of other peoples if they missed a component or put the wrong tag on the object

**Comment by DigitalIver** [comment]
hmm gonna find what cause this issue else where
