### ISSUE TITLE
Config to disable moon danger ratings

### ISSUE THREAD

**Issue by hoodshine** [HolographicWings/LethalExpansion#4]
Spoils the initial surprise when finding out the danger of going to the moon and causes players to plan a little too much.

**Comment by HolographicWings** [comment]
> Spoils the initial surprise when finding out the danger of going to the moon and causes players to plan a little too much.

okay, i will add it maybe tomorrow

**Comment by broilerosu** [comment]
maybe make a standalone mod for the moon danger ratings

**Comment by HolographicWings** [comment]
> maybe make a standalone mod for the moon danger ratings

I don't plan to do any standalone mods sorry

and btw @hoodshine , your request is done, i'm doing some fixing and additions before to release
