### ISSUE TITLE
[BUG] Version 1.2.16 does infinite calls when people join causing huge stutter

### ISSUE THREAD

**Issue by Dantoresco** [HolographicWings/LethalExpansion#40]
On version 1.2.16 the log shows infinite RPC handler messages anytime someone joins, the more people joining the worse it gets until it's unplayable. I also noticed the modded moons were not loading.
I tested it on different versions and all of this works fine on 1.2.15

[LogOutput.log](https://github.com/HolographicWings/LethalExpansion/files/13732248/LogOutput.log)

**Comment by HolographicWings** [comment]
> On version 1.2.16 the log shows infinite RPC handler messages anytime someone joins, the more people joining the worse it gets until it's unplayable. I also noticed the modded moons were not loading. I tested it on different versions and all of this works fine on 1.2.15
> 
> [LogOutput.log](https://github.com/HolographicWings/LethalExpansion/files/13732248/LogOutput.log)

You have 57 errors, i can't support an issue with a modpack burried of errors

**Comment by Dantoresco** [comment]
Reinstaled everything from a mod manager and most of the issues got solved included this one. Sorry about that.
