### ISSUE TITLE
Lite version of this mod?

### ISSUE THREAD

**Issue by Fredolx** [HolographicWings/LethalExpansion#41]
Would it be possible to have a seperate mod which only implements the custom moon support? Custom moons mods depend on this mod but it packages too much and might conflict with other mods. I understand if this request does not interest you, thank you for your work.

**Comment by Fredolx** [comment]
Sorry, I just noticed there's another issue pertaining to this. Feel free to close it.

**Comment by HolographicWings** [comment]
yes, a topic already been opened for this
