### ISSUE TITLE
help pls, how to install the mod? 

### ISSUE THREAD

**Issue by K1sk3** [HolographicWings/LethalExpansion#43]
like where should I upload files and what kind? I read some questions, but people generally cannot formulate the idea...I seem to have installed everything, but when I go into the game and click on these..mod settings, in short, the usual settings open

**Comment by HolographicWings** [comment]
> like where should I upload files and what kind? I read some questions, but people generally cannot formulate the idea...I seem to have installed everything, but when I go into the game and click on these..mod settings, in short, the usual settings open

Use r2modman to install it if you struggle with manual installation

**Comment by GodOfMelons** [comment]
can you please just give us a few steps on how to install MANUALLY? i dont feel like installing extra programs just for this

**Comment by HolographicWings** [comment]
> can you please just give us a few steps on how to install MANUALLY? i dont feel like installing extra programs just for this

you have to install BepInEx, follow their tutorial
when it's done you can create a Plugins folder in the BepInEx folder, and drop the mods here
in short, drop the mod in BepInEx/Plugins
i advice you to create a folder to separate each mods, like BepInEx/Plugins/LethalExpansion
![image](https://github.com/HolographicWings/LethalExpansion/assets/19623115/8238fbed-f9a7-4b91-a215-22549eddba8c)
