### ISSUE TITLE
internal class Terminal_Patch vs public class Terminal_Patch

### ISSUE THREAD

**Issue by Coockie1173** [HolographicWings/LethalExpansion#44]
Is there any particular reason the Terminal_Patch is internal rather than public? I need to access newMoons but since Terminal_Patch is internal I can't access it from an "outside" assembly.

**Comment by HolographicWings** [comment]
> Is there any particular reason the Terminal_Patch is internal rather than public? I need to access newMoons but since Terminal_Patch is internal I can't access it from an "outside" assembly.

i will make it public in next update
new classes are internal by default, i don't always think about making them public
