### ISSUE TITLE
crashing

### ISSUE THREAD

**Issue by gaugesletkolen** [HolographicWings/LethalExpansion#45]
game crashes when i load up a new moon

**Comment by gaugesletkolen** [comment]
[Logoutput.txt](https://github.com/HolographicWings/LethalExpansion/files/13763509/Logoutput.txt)

**Comment by HolographicWings** [comment]
> [Logoutput.txt](https://github.com/HolographicWings/LethalExpansion/files/13763509/Logoutput.txt)
> 

Hello
Your log don't give any clue of what happening
What other mods are you using and does the crash still happen when LE is the only mod used ?

**Comment by gaugesletkolen** [comment]
i figured out it was a compatibility issue with Vanilla Plus Addition
