### ISSUE TITLE
Custom dungeon compatibility with LethalLib

### ISSUE THREAD

**Issue by Coockie1173** [HolographicWings/LethalExpansion#46]
Is there a decent way to easily integrate a custom dungeon (which is built via LethalLib) into a custom planet? Or rather: force a custom flow type on a moon? If not via LethalLib, just a native implementation for this SDK?
I'm down to look into it myself and submit a PR if I do figure it out, but I figured I'd ask nevertheless

**Comment by HolographicWings** [comment]
> Is there a decent way to easily integrate a custom dungeon (which is built via LethalLib) into a custom planet? Or rather: force a custom flow type on a moon? If not via LethalLib, just a native implementation for this SDK? I'm down to look into it myself and submit a PR if I do figure it out, but I figured I'd ask nevertheless

i dunno how LethalLib implement the new dungeons, if it's a new normal flow i guess putting it's ID in the moon asset would be enough
native dungeon support for SDK is planned tho

**Comment by Coockie1173** [comment]
> > Is there a decent way to easily integrate a custom dungeon (which is built via LethalLib) into a custom planet? Or rather: force a custom flow type on a moon? If not via LethalLib, just a native implementation for this SDK? I'm down to look into it myself and submit a PR if I do figure it out, but I figured I'd ask nevertheless
> 
> i dunno how LethalLib implement the new dungeons, if it's a new normal flow i guess putting it's ID in the moon asset would be enough native dungeon support for SDK is planned tho
[https://github.com/EvaisaDev/LethalLib/blob/60d42612d19dbe329175a80dfc41bc601a0ec3eb/LethalLib/Modules/Dungeon.cs#L28](url) following the logic from LethalLib it's just adding it as a flow somewhere down the line, so it shouldn't be that hard. Only issue is I won't/can't know which flow ID LethalLib used for my custom flow, so I can't really assign it to my custom moon. At least I don't think? Again might look into it later myself and submit a PR if I figure something out

**Comment by HolographicWings** [comment]
> > > Is there a decent way to easily integrate a custom dungeon (which is built via LethalLib) into a custom planet? Or rather: force a custom flow type on a moon? If not via LethalLib, just a native implementation for this SDK? I'm down to look into it myself and submit a PR if I do figure it out, but I figured I'd ask nevertheless
> > 
> > 
> > i dunno how LethalLib implement the new dungeons, if it's a new normal flow i guess putting it's ID in the moon asset would be enough native dungeon support for SDK is planned tho
> > [https://github.com/EvaisaDev/LethalLib/blob/60d42612d19dbe329175a80dfc41bc601a0ec3eb/LethalLib/Modules/Dungeon.cs#L28](url) following the logic from LethalLib it's just adding it as a flow somewhere down the line, so it shouldn't be that hard. Only issue is I won't/can't know which flow ID LethalLib used for my custom flow, so I can't really assign it to my custom moon. At least I don't think? Again might look into it later myself and submit a PR if I figure something out

yes, but a dungeon flow is a matrix of 40 prefabs, with specific elements in each prefab to define where are the doors, where can be the scraps, where can be the fireexists, etc
it's more complex than add a flow down the line

**Comment by Coockie1173** [comment]
> > > > Is there a decent way to easily integrate a custom dungeon (which is built via LethalLib) into a custom planet? Or rather: force a custom flow type on a moon? If not via LethalLib, just a native implementation for this SDK? I'm down to look into it myself and submit a PR if I do figure it out, but I figured I'd ask nevertheless
> > > 
> > > 
> > > i dunno how LethalLib implement the new dungeons, if it's a new normal flow i guess putting it's ID in the moon asset would be enough native dungeon support for SDK is planned tho
> > > [https://github.com/EvaisaDev/LethalLib/blob/60d42612d19dbe329175a80dfc41bc601a0ec3eb/LethalLib/Modules/Dungeon.cs#L28](url) following the logic from LethalLib it's just adding it as a flow somewhere down the line, so it shouldn't be that hard. Only issue is I won't/can't know which flow ID LethalLib used for my custom flow, so I can't really assign it to my custom moon. At least I don't think? Again might look into it later myself and submit a PR if I figure something out
> 
> yes, but a dungeon flow is a matrix of around 40 prefabs, with specific elements in each prefab to define where are the doors, where can be the scraps, where can be the fireexists, etc it's more complex than just add a flow down the line

yeah I know, but I got it working perfectly with LethalLib (setting up all the prefabs was a ton of work but I got it working), so it can't be too bad to port over, idk I'll have a look at it

**Comment by HolographicWings** [comment]
> > > > > Is there a decent way to easily integrate a custom dungeon (which is built via LethalLib) into a custom planet? Or rather: force a custom flow type on a moon? If not via LethalLib, just a native implementation for this SDK? I'm down to look into it myself and submit a PR if I do figure it out, but I figured I'd ask nevertheless
> > > > 
> > > > 
> > > > i dunno how LethalLib implement the new dungeons, if it's a new normal flow i guess putting it's ID in the moon asset would be enough native dungeon support for SDK is planned tho
> > > > [https://github.com/EvaisaDev/LethalLib/blob/60d42612d19dbe329175a80dfc41bc601a0ec3eb/LethalLib/Modules/Dungeon.cs#L28](url) following the logic from LethalLib it's just adding it as a flow somewhere down the line, so it shouldn't be that hard. Only issue is I won't/can't know which flow ID LethalLib used for my custom flow, so I can't really assign it to my custom moon. At least I don't think? Again might look into it later myself and submit a PR if I figure something out
> > 
> > yes, but a dungeon flow is a matrix of around 40 prefabs, with specific elements in each prefab to define where are the doors, where can be the scraps, where can be the fireexists, etc it's more complex than just add a flow down the line
> 
> yeah I know, but I got it working perfectly with LethalLib (setting up all the prefabs was a ton of work but I got it working), so it can't be too bad to port over, idk I'll have a look at it

The difference is I don't put any vanilla or external script in the SDK
I'll have to rebuild every fields
Look how are made the moons in the SDK
The SDK build 5/6 objects from one

**Comment by Coockie1173** [comment]
> > > > > > Is there a decent way to easily integrate a custom dungeon (which is built via LethalLib) into a custom planet? Or rather: force a custom flow type on a moon? If not via LethalLib, just a native implementation for this SDK? I'm down to look into it myself and submit a PR if I do figure it out, but I figured I'd ask nevertheless
> > > > > 
> > > > > 
> > > > > i dunno how LethalLib implement the new dungeons, if it's a new normal flow i guess putting it's ID in the moon asset would be enough native dungeon support for SDK is planned tho
> > > > > [https://github.com/EvaisaDev/LethalLib/blob/60d42612d19dbe329175a80dfc41bc601a0ec3eb/LethalLib/Modules/Dungeon.cs#L28](url) following the logic from LethalLib it's just adding it as a flow somewhere down the line, so it shouldn't be that hard. Only issue is I won't/can't know which flow ID LethalLib used for my custom flow, so I can't really assign it to my custom moon. At least I don't think? Again might look into it later myself and submit a PR if I figure something out
> > > 
> > > 
> > > yes, but a dungeon flow is a matrix of around 40 prefabs, with specific elements in each prefab to define where are the doors, where can be the scraps, where can be the fireexists, etc it's more complex than just add a flow down the line
> > 
> > 
> > yeah I know, but I got it working perfectly with LethalLib (setting up all the prefabs was a ton of work but I got it working), so it can't be too bad to port over, idk I'll have a look at it
> 
> The difference is I don't put any vanilla or external script in the SDK I'll have to rebuild every fields Look how are made the moons in the SDK The SDK build 5/6 objects from one I can't buy DunGen to place it in the SDK neither, this is not legal The goal of the SDK is to do everything with embed HUD The amount of work is not same

Hmm right okay, I see what you're getting at no worries!
In that case I'll have to make my plugin the messenger between the two libraries, mind if I submit a PR that makes all classes public rather than internal for this instead then?

**Comment by HolographicWings** [comment]
yes, you can do this PR
i'll made it in next update anyway
for now i'm taking 3/4 days of resting

**Comment by Coockie1173** [comment]
No worries!
Happy Holidays!
