### ISSUE TITLE
can't use this mod with any other map size editors

### ISSUE THREAD

**Issue by Slydylan** [HolographicWings/LethalExpansion#48]
I found a map *length* multiplier mod that cannot run when lethal expansion is taking over the dungeon generator values. Can you please add a disable feature in the config like the one you have for quota settings? 
Your map size multiplier seems to generate in a very stressful way for the game where the length multiplier increases distance between exits and seems to work in a very efficient manner (i can set this one for 30x and get into the dungeon, walk around for a while and see no performance decrease.). It'd be great to use your mod and have the custom moons but I can't use increased map size at the performance levels that your multiplier creates

edit: i have an rx 6800s with a ryzen 9 6900HS and 16 gigs ram. when i use your map multiplier around 4.5x the game seems to buckle. my resources won't be used fully but the game will slow down significantly. 
the map length generator i set to 30x and honestly didnt see any performance decrease but can actually measure the extra time it takes to create the world (about as long as it takes when i set your mod to 10x).

**Comment by HolographicWings** [comment]
> I found a map *length* multiplier mod that cannot run when lethal expansion is taking over the dungeon generator values. Can you please add a disable feature in the config like the one you have for quota settings? 
> Your map size multiplier seems to generate in a very stressful way for the game where the length multiplier increases distance between exits and seems to work in a very efficient manner (i can set this one for 30x and get into the dungeon, walk around for a while and see no performance decrease.). It'd be great to use your mod and have the custom moons but I can't use increased map size at the performance levels that your multiplier creates
> 
> edit: i have an rx 6800s with a ryzen 9 6900HS and 16 gigs ram. when i use your map multiplier around 4.5x the game seems to buckle. my resources won't be used fully but the game will slow down significantly. 
> the map length generator i set to 30x and honestly didnt see any performance decrease but can actually measure the extra time it takes to create the world (about as long as it takes when i set your mod to 10x).

Both mods seems to multiply the size, so it's exponential
I could add a compatibility setting as for Brutal company plus
Send me the link of the other mod you use please

But about the exits I can't do anything, the exit amount is patched to make them independent of the dungeon Flow
It's obligated for the moons maked with the SDK

**Comment by Slydylan** [comment]
here's that mod https://thunderstore.io/c/lethal-company/p/femboytv/LethalAdjustments/
yes please a compatibility mode would be great
using your map multiplier by itself seems to cause performance issues but it could be something else too.
i tried your mod with this one and noticed not an exponential increase but probably a compatibility mode on the part of lethal adjustments. though there's nothing written about it

**Comment by HolographicWings** [comment]
i'm watching about this mod
Just be aware the values that the mod provides are not vanilla by default
vanilla map size multiplier is 1.5
vanilla scrap amount is 1
and vanilla scrap value is 0.4

**Comment by HolographicWings** [comment]
> here's that mod https://thunderstore.io/c/lethal-company/p/femboytv/LethalAdjustments/ yes please a compatibility mode would be great using your map multiplier by itself seems to cause performance issues but it could be something else too. i tried your mod with this one and noticed not an exponential increase but probably a compatibility mode on the part of lethal adjustments. though there's nothing written about it, as extreme increases to the map size usually create a relative increase in load time but with your mods together i noticed no extra loading time
> 
> "adjusts the multiplier for the total length of the generated map (not size, but length from the main entrance to the emergency exit afaik)" verbatim from his mod page. my experience with your mod showed a difference, where when i use your multiplier the fire exit is still always near the entrance. but with lethal adjustments the distance between exits is being multiplied and the map generates a different way
> 
> edit: to clarify this mod doesn't change the exits in any way it just changes the distance the map is supposed to have between said exits

i'm watching about this mod
Just be aware the values that the mod provides are not vanilla by default
vanilla map size multiplier is 1.5
vanilla scrap amount is 1
and vanilla scrap value is 0.4

**Comment by HolographicWings** [comment]
https://github.com/HolographicWings/LethalExpansion/releases/tag/v1.3.6

**Comment by Slydylan** [comment]
strange. thank you for that.
I don't know what's different then? I tested your mods together and found that lethal adjustments doesn't take effect if your mod is running.
Question is, why did he say the multiplier is different from size if it's the same.. and also why does it run so well at higher values when your multiplier didn't.
It is probably more to do with my computer and maybe something else in the game. I dunno.
Thanks for being so cool about it

**Comment by HolographicWings** [comment]
> strange. thank you for that. I don't know what's different then? I tested your mods together and found that lethal adjustments doesn't take effect if your mod is running. Question is, why did he say the multiplier is different from size if it's the same.. and also why does it run so well at higher values when your multiplier didn't. It is probably more to do with my computer and maybe something else in the game. I dunno. Thanks for being so cool about it

because they patch the same thing and LE should load after
i dunno about the performance issue, i don't experiment any

**Comment by Slydylan** [comment]
got it. in the future if you want some help with debugging & testing i certainly don't mind doing so
