### ISSUE TITLE
Drop Pod Not Appearing

### ISSUE THREAD

**Issue by Zekrodiak** [HolographicWings/LethalExpansion#5]
Drop pod doesn't appear on WaterRidge when purchasing items. 

Also, I can't scan main entrance on WaterRidge.

P.S I think it would be a cool idea if the company had it's own moon. I see that it's the same as Experimental.

**Comment by HolographicWings** [comment]
ye it's normal, theres no drop pod on the map
drop pod and ladders are two of the next features in the SDK

**Comment by Zekrodiak** [comment]
ah I see. hope it get's added soon. love your map! ❤️

**Comment by HolographicWings** [comment]
Added in 1.2.0

**Comment by Zekrodiak** [comment]
Omg! Yes finally! You freaking rock dude! 🤜🤛

**Comment by HolographicWings** [comment]
> Omg! Yes finally! You freaking rock dude! 🤜🤛

still not sync on the network, i try to fix it
