### ISSUE TITLE
Wateridge & Christmas Event Maps Issues

### ISSUE THREAD

**Issue by FrostGuardian0** [HolographicWings/LethalExpansion#51]
Hello, there. This account has been made with the sole purpose of complaining.
I would like to list my issues regarding the maps that come with the LethalExpansion & LethalSDK mods since, as a mod player, this are insanely useful and bring good additions to the game. Except them moons.

(TL:DR - Wateridge is mid, lacks door textures, has no uniqueness to it and falls short on optimizations; Xmas Village is absolute ass, has many problems and generally sucks. My main suggestion would be to separate moons from the toolset).

- Wateridge
1. Main Entrance & Emergency Exit doors have no texture
2. The bonfire in the beginning area is a nice addition, but deals massive damage and persists after stepping off. I know that fire burns, but it would be better if it did less damage (if persistent after stepping off) or leave the current damage if it did not persist after stepping off.
3. Stairwell is pitch-black. Since the map clearly goes for a medieval-esque vibe, maybe adding some torches or lanterns, as there are in other places around the map, would be great at making the ambience better.
4. Leaving the Moon puts you in the Limbo. You're stuck in a perpetual "Waiting for the ship to land" state. That is perhaps one of the worst problems a mod could have.
5. The map is too small and doesn't have any remarks on its outside. I know this might sound dumb, but unlike most maps, this one doesn't have anything going for it. It's small and pretty straight to the point. For an S Rank map, that's in my opinion bad. It feels as an attempt to replace Experimentation, but even that moon has something special. Vow has its brittle bridge, Offense it's... damned turrets, March its many emergency entrances, Titan its long (and dangerous) stairwell, but Wateridge offers nothing. It's cool and aesthetic, but there are no unique dangers. Other than the fire.

If I may suggest something (as I don't want to just complain), I would recommend adding some unique enemy to the moon. Since there's an abundance of water, why not some sea-related monster? Even if it's just a re-skin of the Bunker Spiders to make them Crabs would be more than enough. Or even adding traps and map-hazards. The floor is wood-textured, so making weak planks that break if you're too heavy and could potentially drown you, akin to Vow's bridge, would already give it something to go for. Or, instead of falling through the, have tentacles that spawn during the night that pull the Amazon workers in and drown them by force. Or, hell, why not both? They break during the day and tentacles attach during the night. Wateridge has a lot of potential as a good map, and I do hope to see it get fixed and expanded.

- Christmas Village Event
(Now, for this one I won't be as kind. Not one bit.)
1. The map is absurdly big. What is the point of walking through the snow for nearly 2 minutes just to reach the entrance? Not even Rend/Dine force you to such BS. Why have the ship land SO far away, when there's so much space in the village and its near surroundings.
2. Oh, boy. This map suffers the opposite from Wateridge. It's gigantic. Bigger than Rend/Dine I dare say. There is absolutely no purpose for the map to be so big when you only need so little to explore as, just like Wateridge, there is literally nothing there. And since the map is so large, with so much snow particles and foliage and all that, it stutters like hell. Not even 3 seconds in between before I get massive frame drops while I'm outside, making even walking a living hell.
3. The emergency exits. Why? Why do they take you to Narnia? Where do you go to reach back to the mainland? I know they leave you just under the main entrance, as the scanner points it above you (although it tends to be inaccurate even in vanilla), but that still begs the question "How the hell do I even leave?" You're in a dark, rocky cave that's bumpy and hard to navigate and leads you on and on and on to NOWHERE. There is no point trying to find a path out, as (again) the stutters make it so not worth the effort. It's better to hop back in the facility and find the main entrance. I've found 2 emergency exits that fit the previous description, while one has a raft that has no collision and kills you as you fall into the water. If there's any more exits, god bless. Whatever god might even want to do that.
4. It has door textures, at least.
5. And, just as Wateridge, it lacks character. It has nothing unique nor special to it. 'The Christmas spirit' you may say... No. It remains generic and stale, as all it has is some colored presents and a large Pine Tree. 'The cave system' you might add... No. Maybe, but it falls mega flat. It's awful to navigate and too long to bother. It would've been nice if that's what all the Moon was about. Some sort of underground cave town... like Undertale, actually. Snowdin, somehow, manages to capture an even better Christmas spirit than this moon when all it has is snow (and more skeletons and puns than it). As I said: Unfortunately, Xmas Village has nothing to offer. Just like McAfee, all it does is take space from your computer storage.

Unfortunately, for this map (even if it is 'limited time') there's no saving in its current iteration. There is no reason for it to be so big, there is no reason for it to have pointless emergency exits, there is no reason for it to have a Landing-to-Entrance path as long as it does. This doesn't put me into the christmas spirit, it puts me into the 'Go complain to the developer' spirit, and that's never a good spirit to have.

Then, hoping to answer some questions that might come with this report.
- If you don't like the maps, why just not even go to them?
It's not about whether I like them or not. Mods that includes moons aren't that small. They aren't adding just a suit, or a bunch of scrap, they're adding an entire map with configurations, and enemy weights, and scrap totals, etc. If they're going to be WITHIN the  mod, without me being able to chose if I want them installed or not, then... they have to be good. They have the worth the space they're taking and give a fun experience to me and my friends. Wateridge has the potential, Christmas Village does not. And since they aren't worth playing, I would like to not have them installed.
- Why not uninstall LE & LSDK?
Because they're the tools that make many mods work. Not only new Moons, but also Scraps. I can't delete them if I want, perse, a damn Floppa Fumo. Who doesn't want a Floppa Fumo? There's also other Moons, like Orion & Aquatis, which are incredibly good and unique. Which, if I deleted said mods, I wouldn't be able to play. Those mods that LE/LSDK support share way more fun and value than what Wateridge (in its current version, as of 12/26/2023) and XMas Village offer. And, if I even have to say, No. I won't just 'delete all mods that support it'. I play modded because it's way more entertaining than Vanilla, that should be obvious.
- There must be a way to delete them from the files, just do that.
bruh. I don't doubt that's an option, I know it most definetely is, but that's not something I can bother doing. Or creating some sort of support mod that removes them or something. I have no knowledge modding, if barely some texture changing.

Finally, my last suggestion.
Make the moons a different mod. I, as I'm sure many others too, downloaded these mods sorely for the support they grant the actual working moons and scraps. They add useless storage to my HardDrive, and overall make the performance of the game worse. Wateridge, as a standalone, would be great with the right hands working on it (I know I keep bringing it). XMas village, however... was too ambitious. That's something that the game developers should've made, if they wanted to make it. Why not decorate Wateridge instead with the Winter spirit instead? Also, the concept of a limited time moon isn't that appealing, if I may say. Assuming Xmas village was a banger, then I'd be bummed out once it was removed. And surely many others would want it to stay as its standalone, maybe even someone getting the files and releasing it on their own (assuming it's even worth it, which is not). Again, I have no knowledge about modding. I have no idea how hard would it be to separate the moons from the pack without breaking something. But it would absolutely be amazing if that could be a thing.

That was all. Happy (late) Christmas, and (early) New Year. If there's any issue with my report, I'll gladly listen to what I got wrong or what fell short of the truth, etc. 
If you think I was too harsh with Xmas Village. I was.

**Comment by HolographicWings** [comment]
@FrostGuardian0 
Maybe you could make your own maps instead of complaining
Wateridge is a demo scene used for testing
Christmas village was made just for Christmas and will be removed next week

No offense but your complains have absolutely no goal
Especially complaining about the size of the map or the texture of the doors

**Comment by FrostGuardian0** [comment]
@HolographicWings Well, you said it yourself. "Didn't even read half of it". I know I'm not one to demand (which I didn't), but I can suggest. And you were definitely more aggressive to me than what I was to you. I was mostly aggressive to your maps which are a detriment of the mod, and I even try to give my share on how they can be improved and feel more like an in-game moon. If that's not your plan, then that's also fine. But please, this time, read/listen what others have to say to an end before making your conclusions. "Didn't even read half" makes you look worse than what you probably intend. There's a time where its right to shut others down, and a time where its not. In a issue report? Not the time. Give me time of day as I am trying to do here with you.

"Make your own maps". If you had read "more than half" you would've known that I'm not skilled at modding whatsoever. Even if there's "no coding" as you say. It would still take me time. Maybe, with this, you though I insulted your skill and the time it takes to do what you're doing. I did not. I understand how hard doing something as little as making a turret move can be incredibly difficult. I don't need knowledge of my own to see others problems. I apologize if at any point of the first half it came of in that insulting manner, it was not my intention.

"Wateridge is a demo scene used for testing as the mod need bug report and not silly game design complains. Christmas village was made just for Christmas and will be removed next week". Then why have it in the mod files? If it's not meant to be finished, why should I even have it? Demo implies that there will be more to it. Testing, I get. Then address the actual complains of the infinite loading screen, or insta-killing fire. frame drops, pointless Exit doors, etc. None of which you did. Adding a temporary map is a bad idea, because it might never leave enough time to enjoy all it has. Xmas village has nothing to enjoy, than why not make Wateridge winter themed temporarily? I might be repeating myself, but you didn't "read more than half". Also, game-design can definitely fit in bug-reports. Maybe not the ones I gave. For example, the storm in Xmas Village and its abundant foliage. Those are causing problems within the game, while they are design choices.

"If you took more time to test things or read the other issues instead of writing this you would have seen you can remove the template module". That's by far your most fair response. Yes, I should've read other issues to get to know what I can do about it more before posting, I'll take the L there. But, if it's a client side thing and all my friends gotta do the same on their files... I don't think they will be as thrilled. We all rather have a functional game than accidentally break something.

"I passed 10h/day on the mod and the SDK during a whole month to make new moons possible which is an heavy engine restrictions bypass. And it's still far to be stable and finished. Everyone know Wateridge is a technical demo and I don't care about it's estethic". I'll most likely sound rude here, but if you don't care about the maps, if they're not your priority... then why make them? I know. "To test the tools", but must you have in the files your testing if it means having a map that breaks the game 50/50 when you try to leave it? If it means having a heavier mod when it's most likely not necessary for us, the players? I know why the mod is heavy, but I also know why its heavier than it should. Something that, again, you would've known if you had read "more than half".

"No offense but your complains have absolutely no goal. Especially complaining about the size of the map or the texture of the doors". And to this I take massive offense. My complains do have a goal. I don't have to explain it here, since it's probably in the half you didn't read. Never jump into conclusions, please. I'll give you that complaining about the door textures is mostly meaningless and can be overlooked, I agree. But the size of the map absolutely matters. You can have a map as big as the Sahara Desert, and just as empty as it. Just like the village. Wateridge is not as big of a problem, since it's small and gives that 'stranded at sea' illusion. Map size takes space in storage and specially when its filled with foliage and particles. Again, maybe you'd know that if you had read the entire thing. My goal is to see a better expansion that _feels like an expansion_. I apologize for my rudeness, again, but your moons don't grant that as they are now. Even if they're 'test grounds'.

"Fix the vanilla node collider". Again, I don't know how to do that and I won't try in fear of breaking something I shouldn't.

And finally, "So send the same message in one year when the SDK will be entirely finished". That would've been the perfect ending to a well thought out response. But yours fell flat and nearly insulting. I know you must be a one man doing all of this, or a small group of friends helping you out, but being professional is always important. I agree that I wasn't all professional either, but at least I though deeply of what I was writing (even if I wasn't as knowledged) instead of "I didn't read half of that". Brother, you pulled an 'i aint readin allat' on me. At least digest all of what I have to say before shutting me down.

But alas, if you won't listen now, I highly doubt you'll listen... 1 day later. As you recommend, I will wait my time and see how far this mod goes. And once it's finished, then maybe you'll have more time to focus on the maps you clearly don't care about. _Then_ might it be fair to complain of the same things? No. You showed me now how those maps are just for testing, then they might as well be gone next year when you no longer need to improve the toolset. Just as they will be gone later, they might as well be gone now.

I repeat my last suggestion, from the report you didn't read, here. Separate the moons from the tools, and it'll be easier knowing what you have problems with. A mod for your moons that are all for testing, and the mods for the tools that help make and improve those moons. People will know what they're getting into, they'll be more willing to help you out if they see unfinished moons, etc. That way, you might avoid more Me-s on the future. And as I said last time, I absolutely know nothing of how hard this could be and I would not like to sound like a prick by just thinking its easy. I know its hard. But worth an attempt.

Hoping you read "more than half" this time, Merry Christmas and Happy New Year.
