### ISSUE TITLE
Friend can't join

### ISSUE THREAD

**Issue by CelestaGlacier** [HolographicWings/LethalExpansion#53]
Game version v45. Mod version 1.3.6
After installing mod, as host everything work correctly. But when my friend try to join me (same version of game and mod) he get "An error occurred" no matter what. Same of my friend is host, and I try to join him. None other mods is installed.

**Comment by CelestaGlacier** [comment]
What do mean my "modules"? If you mean folder "modules" in "plugins" than we have same (we installed only pure Lethal Expansion). Here is logs.
[MyOwnLogs.log](https://github.com/HolographicWings/LethalExpansion/files/13780020/MyOwnLogs.log)
[MyFriendLogs.log](https://github.com/HolographicWings/LethalExpansion/files/13780021/MyFriendLogs.log)

**Comment by HolographicWings** [comment]
> What do mean my "modules"? If you mean folder "modules" in "plugins" than we have same (we installed only pure Lethal Expansion). Here is logs. [MyOwnLogs.log](https://github.com/HolographicWings/LethalExpansion/files/13780020/MyOwnLogs.log) [MyFriendLogs.log](https://github.com/HolographicWings/LethalExpansion/files/13780021/MyFriendLogs.log)

in your own logs
[Warning:LethalExpansion] Illegal use of reserved Asset Bundle name: oldseaport at: E:\Lethal Company\BepInEx\plugins\Modules\oldseaport.lem.
[Warning:LethalExpansion] Illegal use of reserved Asset Bundle name: templatemod at: E:\Lethal Company\BepInEx\plugins\Modules\templatemod.lem.

the oldseaport and templatemod must be in same folder as the mod (E:\Lethal Company\BepInEx\plugins\2 in your case)
it's a safety think to ensure that people who make their own modules will not overwrite theses two ones with their own edited versions which can cause issues

**Comment by CelestaGlacier** [comment]
Okay. Ye. Everything fixed now. We spend 2 days of trying to fix it, before posting here. Thx man

**Comment by HolographicWings** [comment]
> Okay. Ye. Everything fixed now. We spend 2 days of trying to fix it, before posting here. Thx man

Always read logs, theres generally a clue
