### ISSUE TITLE
How do I disable the Moons that come with this mod?

### ISSUE THREAD

**Issue by Frewsty** [HolographicWings/LethalExpansion#59]
I like this Mod as a library mod but I'm not a fan of the modded moons (Christmas Village, Wateridge)

Is there a way to disable these or is there no option?

If there is no option, can you please add one or make a separate version of the mod that doesn't include the moons?

Thanks.

**Comment by HolographicWings** [comment]
remove the templatemod.lem
but i leave them here because the mod and sdk still need testing and debug

**Comment by Frewsty** [comment]
Can I suggest you add a config to toggle the use of these moons?

A lot of modded moons use this mod as a prerequisite, and I'd only like to use those moons.

Thanks for the reponse.

**Comment by HolographicWings** [comment]
> Can I suggest you add a config to toggle the use of these moons?
> 
> A lot of modded moons use this mod as a prerequisite, and I'd only like to use those moons.
> 
> Thanks for the reponse.

it's not that simple
if i add configs for modules, that would be in the SDK, not only for the template
making everyone able to make their own configs
so load theses configs dynamically and build an HUD about it

**Comment by oudehenky** [comment]
o/

I removed the templatemod.lem but the christmas villages are still present.

Did I do anything wrong or is there another file to remove?

**Comment by Frewsty** [comment]
My bad, I'm not a modder so I don't understand how difficult configs are to set up.

Alternate Suggestion, though, could you maybe make the Christmas Village and Wateridge maps a separate mod that are labelled as prerequisites to this mod? That way people still get it by default but have the ability to easily remove them.

I noted how you said they were for testing/debugging, and if so, why not just make them separate mods for people who want to test/debug?

I use Thunderstore, and the lack of convenience in removing these maps may be a big turn off for people using this mod in the future. I don't think the maps fit Lethal Company's style at all, and I'd very much appreciate a way to disable these maps without having to dig around in game files, which a lot of people don't want to do.

Still though, I appreciate you giving me a cohesive way of getting rid of these moons. Thank you.

**Comment by HolographicWings** [comment]
> o/
> 
> I removed the templatemod.lem but the christmas villages are still present.
> 
> Did I do anything wrong or is there another file to remove?
> 
> RE: There was another .lem file named "christmasvillage.lem". However upon removing this file my game would crash.

The Christmas village.lem contain only assets
Read the logs to be sure the template is really removed and not loaded

**Comment by HolographicWings** [comment]
> My bad, I'm not a modder so I don't understand how difficult configs are to set up.
> 
> Alternate Suggestion, though, could you maybe make the Christmas Village and Wateridge maps a separate mod that are labelled as prerequisites to this mod? That way people still get it by default but have the ability to easily remove them.
> 
> I noted how you said they were for testing/debugging, and if so, why not just make them separate mods for people who want to test/debug?
> 
> I use Thunderstore, and the lack of convenience in removing these maps may be a big turn off for people using this mod in the future. I don't think the maps fit Lethal Company's style at all, and I'd very much appreciate a way to disable these maps without having to dig around in game files, which a lot of people don't want to do.
> 
> Still though, I appreciate you giving me a cohesive way of getting rid of these moons. Thank you.
> 
> 

The one who want testing and debug is me
While I'll have issues to fix I'll let the to have the maximum of reports possible
LE is not finished
Conciser the mod being WIP
It's planned to move the template from the mod but not for yet

**Comment by Frewsty** [comment]
okay, thanks

**Comment by oudehenky** [comment]
Okay so, removing christmasvillage.lem and seaport.lem lets me launch, but it does NOT let other users join me.

Even if we have a carbon copy save, with the same configs and files it will not let them join.

**Comment by HolographicWings** [comment]
moons moved into another mod
