### ISSUE TITLE
RPC_HANDLER Causing Big Frame Drop and lag

### ISSUE THREAD

**Issue by DigitalIver** [HolographicWings/LethalExpansion#65]
![image](https://github.com/HolographicWings/LethalExpansion/assets/153030687/799553e5-c230-439a-afef-f204c402fa83)
 does anyone know what this mean and how to fix it ?

**Comment by HolographicWings** [comment]
> ![image](https://private-user-images.githubusercontent.com/153030687/293586374-799553e5-c230-439a-afef-f204c402fa83.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxMzU0NjUsIm5iZiI6MTcwNDEzNTE2NSwicGF0aCI6Ii8xNTMwMzA2ODcvMjkzNTg2Mzc0LTc5OTU1M2U1LWMyMzAtNDM5YS1hZmVmLWYyMDRjNDAyZmE4My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwMVQxODUyNDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMzZlNjhjMWY3ZjExNjcxMWU1NmM0NzQ0Yzg3OTczY2NjMTVmY2YzYWJiNzM2OTNjYWNmZjJhMTQ4ZGI1OTg3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.FKWQzb75PtS5A4nLaiKweVAW9LD0N0B8RtuSsRiah8Y) does anyone know what this mean and how to fix it ?

incompatibility with another mod
disable all your mods progressively till find which one is not compatible
