### ISSUE TITLE
Finding more incompatibilities

### ISSUE THREAD

**Issue by jamiejoan** [HolographicWings/LethalExpansion#79]
Hi, I'm afraid i found another incompatibility. please let me know what I should do, if i should tell you or the other modder?

NeedyCats by Jordo

there's no cats anywhere in the game when I use this with your mod LethalExpansion

**Comment by HolographicWings** [comment]
> Hi, I'm afraid i found another incompatibility. please let me know what I should do, if i should tell you or the other modder?
> 
> NeedyCats by Jordo
> 
> there's no cats anywhere in the game when I use this with your mod LethalExpansion 

We already worked on this incompatibility
It was supposed to be fixed
Do you use the latest version of needy cats ?

**Comment by jamiejoan** [comment]
it works, my bad! I dont know if i was using the update but the next test run i finally ran into a cat.
