### ISSUE TITLE
MORE MONSTERS 

### ISSUE THREAD

**Issue by CLAPPINURCHEEKS1** [HolographicWings/LethalExpansion#8]
I ran around waterridge and Orion for a while and barely encountered any monsters I found one face sucker and a spore lizard and I got killed by a bracken after going there 14 times and trying to die intentionally I was just running around the maze. I like the new maps and the mod but they both need more monsters in the maps or an adjustable feature for how many can spawn like the loot multipliers. I would try to do something about it myself if I knew how to do that kind of stuff🤣 I would greatly appreciate a feature being added for more monsters or just more monsters In general. other than that all of the other features so far are great and add some nice stuff to make you feel like your doing more in one match I really like it. Keep up the good work👍

**Comment by HolographicWings** [comment]
> I ran around waterridge and Orion for a while and barely encountered any monsters I found one face sucker and a spore lizard and I got killed by a bracken after going there 14 times and trying to die intentionally I was just running around the maze. I like the new maps and the mod but they both need more monsters in the maps or an adjustable feature for how many can spawn like the loot multipliers. I would try to do something about it myself if I knew how to do that kind of stuff🤣 I would greatly appreciate a feature being added for more monsters or just more monsters In general. other than that all of the other features so far are great and add some nice stuff to make you feel like your doing more in one match I really like it. Keep up the good work👍

Well, theses settings are in the SDK
I'm not the creator of orion, I can't change the amount of monsters
But if you use the last version of the mod, Wateridge is supposed to be filled of monsters
At the end of the days there will be around 12 monsters
How much time did you stayed in Wateridge ?

**Comment by CLAPPINURCHEEKS1** [comment]
> > I ran around waterridge and Orion for a while and barely encountered any monsters I found one face sucker and a spore lizard and I got killed by a bracken after going there 14 times and trying to die intentionally I was just running around the maze. I like the new maps and the mod but they both need more monsters in the maps or an adjustable feature for how many can spawn like the loot multipliers. I would try to do something about it myself if I knew how to do that kind of stuff🤣 I would greatly appreciate a feature being added for more monsters or just more monsters In general. other than that all of the other features so far are great and add some nice stuff to make you feel like your doing more in one match I really like it. Keep up the good work👍
> 
> Well, theses settings are in the SDK when the map is made I'm not the creator of orion, I can't change the amount of monsters But if you use the last version of the mod, Wateridge is supposed to be filled of monsters At the end of the days there will be around 12 monsters But there is no global multiplayer for monster spawning as for scraps in the game How much time did you stayed in Wateridge ?

On the most recent update you had I went to waterridge 14 times trying to intentionally die so maybe 1 and a half hours of just running around and didn’t encounter a whole lot. Maybe I was just getting really lucky. I will try to use the last version later today and see if that helps me get monsters more often. I appreciate you telling me about that👍

**Comment by HolographicWings** [comment]
> > > I ran around waterridge and Orion for a while and barely encountered any monsters I found one face sucker and a spore lizard and I got killed by a bracken after going there 14 times and trying to die intentionally I was just running around the maze. I like the new maps and the mod but they both need more monsters in the maps or an adjustable feature for how many can spawn like the loot multipliers. I would try to do something about it myself if I knew how to do that kind of stuff🤣 I would greatly appreciate a feature being added for more monsters or just more monsters In general. other than that all of the other features so far are great and add some nice stuff to make you feel like your doing more in one match I really like it. Keep up the good work👍
> > 
> > 
> > Well, theses settings are in the SDK when the map is made I'm not the creator of orion, I can't change the amount of monsters But if you use the last version of the mod, Wateridge is supposed to be filled of monsters At the end of the days there will be around 12 monsters But there is no global multiplayer for monster spawning as for scraps in the game How much time did you stayed in Wateridge ?
> 
> On the most recent update you had I went to waterridge 14 times trying to intentionally die so maybe 1 and a half hours of just running around and didn’t encounter a whole lot. Maybe I was just getting really lucky. I will try to use the last version later today and see if that helps me get monsters more often. I appreciate you telling me about that👍

What about now ?

**Comment by CLAPPINURCHEEKS1** [comment]
> > > > I ran around waterridge and Orion for a while and barely encountered any monsters I found one face sucker and a spore lizard and I got killed by a bracken after going there 14 times and trying to die intentionally I was just running around the maze. I like the new maps and the mod but they both need more monsters in the maps or an adjustable feature for how many can spawn like the loot multipliers. I would try to do something about it myself if I knew how to do that kind of stuff🤣 I would greatly appreciate a feature being added for more monsters or just more monsters In general. other than that all of the other features so far are great and add some nice stuff to make you feel like your doing more in one match I really like it. Keep up the good work👍
> > > 
> > > 
> > > Well, theses settings are in the SDK when the map is made I'm not the creator of orion, I can't change the amount of monsters But if you use the last version of the mod, Wateridge is supposed to be filled of monsters At the end of the days there will be around 12 monsters But there is no global multiplayer for monster spawning as for scraps in the game How much time did you stayed in Wateridge ?
> > 
> > 
> > On the most recent update you had I went to waterridge 14 times trying to intentionally die so maybe 1 and a half hours of just running around and didn’t encounter a whole lot. Maybe I was just getting really lucky. I will try to use the last version later today and see if that helps me get monsters more often. I appreciate you telling me about that👍
> 
> What about now ?

It is much better now. I tried it out with a friend yesterday and realized there was a lot more monsters. Thank you for the information and updates. I will continue to try it out every update👍
