### ISSUE TITLE
Can someone help? When updating the sdk my old custom moons wont build once in that project.

### ISSUE THREAD

**Issue by lilswisher** [HolographicWings/LethalExpansion#86]
Its keeps giving me an error saying it cant find the specified file in asset builds talking about the moon im trying to export example it says "MARS.lem is unable to be located" in unity while using the sdk to build my moon.

**Comment by lilswisher** [comment]
i copied all files of the moon located under "mods" in unity before changing to the new sdk then put them in that moon mod folder in the mods folder of the new unity sdk version.

**Comment by lilswisher** [comment]
now it wont compile, then when switching back to the old sdk using unity it wont build the moon in that version either, what happened?

**Comment by lilswisher** [comment]
/Desktop/LethalSDK_Project/Assets/AssetBundles/MARS.lem: The system cannot find the file specified.

**Comment by HolographicWings** [comment]
> /Desktop/LethalSDK_Project/Assets/AssetBundles/MARS.lem: The system cannot find the file specified.

You may have two files with same name
It generates conflict
Read the logs in the unity console to know which file exactly

**Comment by lilswisher** [comment]
THANK YOU SO MUCH
