### ISSUE TITLE
Way to damage players? Like a death barrier?

### ISSUE THREAD

**Issue by lilswisher** [HolographicWings/LethalExpansion#89]
do i just slap the damage player c# script you have for us or? ive been trying to figure this one out for a while. - Lethal Moon Team

**Comment by lilswisher** [comment]
Ive tried everything but i just fall through the cube i have set as death barrier. I even copied item dropship deathbarrier build but cant achieve the results?

**Comment by HolographicWings** [comment]
> Ive tried everything but i just fall through the cube i have set as death barrier. I even copied item dropship deathbarrier build but cant achieve the results?

There's a script called Damage Player
You can see it in the fire of wateridge
